-- Migration: Move all images inline into their respective sections
-- Also adds missing I2C video URL and missing RTOS image (page29_img1)

-- ============================================================================
-- LESSON: lesson-t-overview
-- Images: page2_img1 -> "Industry Alignment" section
-- ============================================================================
UPDATE lessons SET content_json = json_set(
  json_remove(content_json, '$.images'),
  '$.sections',
  json('[
    {"title":"Introduction","content":"In this program you will design and implement a fully functioning smartwatch by combining low level driver development, embedded systems programming, and system-level integration.\n\nYou will work on the **LilyGo T-Watch 2020 V3**, a real commercial smartwatch platform, and write production-style firmware entirely in C and C++: the same languages used in industry for resource-constrained embedded systems.\n\n- **C** is used for low-level hardware control and communication\n- **C++** enables modular design, abstraction, and higher-level application logic\n\nThroughout the program you will build your system incrementally using provided training materials, reference implementations, and targeted code examples. These resources are designed to support you without removing the need for engineering decision making.\n\nIf you need help, email **support@shortcct.com** with your specific questions and a zip file including your project directory. Remember, virtual support is available for **3 months** after your product delivery date."},
    {"title":"Recommended Background","content":"This project is designed for students who want hands-on embedded firmware experience. You do not need a lot of experience, but some foundational knowledge is expected.\n\n**Required:**\n- Introductory programming experience in C or C++\n- Comfort with basic programming concepts such as functions, control flow, arrays, and structs\n\n**Helpful:**\n- Introductory exposure to embedded systems\n- Introductory electronics knowledge\n\nIf you find that you are missing some of this background, reach out to us at **support@shortcct.com** and we can explore options to get you up to speed!"},
    {"title":"Industry Alignment","content":"We analyzed the most in-demand skills across 50+ companies hiring embedded systems engineering interns. Below is how the Smartwatch Project aligns with those skills.\n\n**Core Skills** are fully covered in the base project.\n**Extendable Skills** can be developed through optional project extensions and the design challenge.\n**Not Covered** indicates skills that are outside the scope of the core project.","images":[{"url":"https://www.genspark.ai/api/files/s/2D27gI2m","alt":"Industry Alignment Skills Table","caption":"How the Smartwatch Project aligns with in-demand embedded systems skills"}]},
    {"title":"Documentation","content":"Here is the relevant documentation that you will need to use throughout the development of your project:\n\n**Datasheets:**\n- [AXP202 Datasheet](https://linux-sunxi.org/images/2/20/AXP202_Datasheet_v1.0_en.pdf) - Power Management IC\n- [PCF8563 Datasheet](https://www.nxp.com/docs/en/data-sheet/PCF8563.pdf) - Real-Time Clock\n- [ST7789V Datasheet](https://www.displayfuture.com/Display/datasheet/controller/ST7789V.pdf) - Display Controller\n- [FT6236U Datasheet](https://www.buydisplay.com/download/ic/FT6236-FT6336-FT6436L-FT6436_Datasheet.pdf) - Touch Controller\n- [BMA423 Datasheet](https://www.mouser.com/datasheet/2/783/BSCH_S_A0010021471_1-2525113.pdf) - Accelerometer\n\n**Libraries:**\n- [TFT_eSPI Library](https://doc-tft-espi.readthedocs.io/) - Display Graphics Library\n- [AXP202X_Library](https://github.com/lewisxhe/AXP202X_Library) - Power Management Library\n- [BMA423_Library](https://github.com/lewisxhe/BMA423_Library/tree/master) - Accelerometer Library\n\n**Other:**\n- [T-Watch Pinout](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/master/docs/watch_2020_v3.md)\n- [T-Watch Schematic](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/master/Schematic/T_WATCH-2020V03.pdf)"},
    {"title":"Set Up Smartwatch","content":"To set up PlatformIO, this video by DroneBot Workshop is a great resource. It includes installation steps for Linux, MacOS, and Windows. You can download the latest versions of Python and Visual Studio Code.\n\nOnce you have downloaded PlatformIO on your system, watch the following video to set up your environment for our project.\n\nThe following video shows you how to clone our GitHub repository, [short-circuit-projects/smartwatch](https://github.com/short-circuit-projects/smartwatch), to VSCode. This tutorial is done on Windows, so it will look different on Linux or MacOS."}
  ]')
) WHERE id = 'lesson-t-overview';

-- ============================================================================
-- LESSON: lesson-t-files
-- Images: page5_img1 -> "Header File Example", page5_img2 -> "C Source File", page6_img1 -> "C++ Source File"
-- ============================================================================
UPDATE lessons SET content_json = json_set(
  json_remove(content_json, '$.images'),
  '$.sections',
  json('[
    {"title":"File Structure: Headers and Source Files","content":"A well-structured embedded project separates code into **header files** (.h) and **source files** (.c or .cpp). This organization improves readability, enables code reuse, and supports modular development.\n\n**Header Files (.h)**\n- Contain declarations: function prototypes, macros, type definitions\n- Act as the public interface to a module\n- Include guards prevent multiple inclusion\n\n**Source Files (.c or .cpp)**\n- Contain implementations: function definitions, static variables\n- Include their corresponding header file\n- Hide internal details from other modules"},
    {"title":"Header File Example (accel.h)","content":"Header files declare the public interface. They tell other files what functions and types are available without revealing implementation details.\n\n```c\n#ifndef ACCEL_H\n#define ACCEL_H\n\n#include <stdint.h>\n\n// Public function declarations\nvoid accel_init(void);\nint16_t accel_read_x(void);\nint16_t accel_read_y(void);\nint16_t accel_read_z(void);\n\n#endif // ACCEL_H\n```\n\nThe `#ifndef`, `#define`, and `#endif` are **include guards** that prevent the header from being processed multiple times.","images":[{"url":"https://www.genspark.ai/api/files/s/W6YXjNvj","alt":"Header file example showing accel.h","caption":"Header File (accel.h) - Declares the public interface"}]},
    {"title":"C Source File (accel.c)","content":"C source files implement the functions declared in the header. They contain the actual code that runs on the device.\n\n```c\n#include \"accel.h\"\n#include \"i2c.h\"\n\n#define ACCEL_ADDR 0x18\n\nstatic uint8_t accel_buffer[6];\n\nvoid accel_init(void) {\n    i2c_write_reg(ACCEL_ADDR, 0x20, 0x47);\n}\n\nint16_t accel_read_x(void) {\n    i2c_read_bytes(ACCEL_ADDR, 0x28, accel_buffer, 2);\n    return (int16_t)((accel_buffer[1] << 8) | accel_buffer[0]);\n}\n```\n\nNote that `accel_buffer` is declared `static`, making it private to this file.","images":[{"url":"https://www.genspark.ai/api/files/s/cjAQlIAb","alt":"Source file example showing accel.c","caption":"C Source File (accel.c) - Implements the functionality"}]},
    {"title":"C++ Source File (display.cpp)","content":"C++ source files use classes and object-oriented features. The structure is similar to C but with additional capabilities.\n\n```cpp\n#include \"display.h\"\n#include <TFT_eSPI.h>\n\nstatic TFT_eSPI tft;\n\nvoid display_init(void) {\n    tft.init();\n    tft.setRotation(2);\n    tft.fillScreen(TFT_BLACK);\n}\n\nvoid display_text(const char* text, int x, int y) {\n    tft.setCursor(x, y);\n    tft.print(text);\n}\n\nvoid display_clear(void) {\n    tft.fillScreen(TFT_BLACK);\n}\n```\n\nC++ files use `.cpp` extension and can leverage libraries like TFT_eSPI that provide object-oriented interfaces.","images":[{"url":"https://www.genspark.ai/api/files/s/KrdlcPTc","alt":"C++ source file example showing display.cpp","caption":"C++ Source File (display.cpp) - Uses classes and OOP"}]}
  ]')
) WHERE id = 'lesson-t-files';

-- ============================================================================
-- LESSON: lesson-t-pointers
-- Images mapped to sections:
-- page8_img1 -> "Passing by Value vs Pointer"
-- page8_img2 -> "Pointers and Arrays"
-- page9_img1 -> "Pointers to Structures"
-- page9_img2 -> "C++ References"
-- page10_img1 -> "Const Pointers"
-- page11_img1 -> "Pointers in Interrupts and Tasks"
-- ============================================================================
UPDATE lessons SET content_json = json_set(
  json_remove(content_json, '$.images'),
  '$.sections',
  json('[
    {"title":"Introduction to Pointers and References","content":"Pointers and references are fundamental to embedded systems programming. They enable efficient memory usage, direct hardware access, and passing data between functions without copying.\n\nIn embedded systems, you will use pointers to:\n- Access hardware registers at specific memory addresses\n- Pass large data structures efficiently\n- Share data between interrupt handlers and main code\n- Work with arrays and buffers"},
    {"title":"Pointer Basics","content":"A pointer is a variable that stores a memory address. The address-of operator `&` gets a variable''s address, and the dereference operator `*` accesses the value at that address.\n\n```c\nint value = 42;\nint *ptr = &value;    // ptr holds address of value\n*ptr = 100;           // changes value to 100\n```\n\nUnderstanding pointer syntax is critical for embedded development where direct memory manipulation is common."},
    {"title":"Passing by Value vs Pointer","content":"When you pass a variable by value, the function receives a copy. Changes to the copy do not affect the original.\n\nWhen you pass a pointer, the function can modify the original variable through the pointer.\n\n```c\n// Pass by value - cannot modify original\nvoid set_value(int x) {\n    x = 100;  // Only changes local copy\n}\n\n// Pass by pointer - can modify original\nvoid set_value_ptr(int *x) {\n    *x = 100;  // Changes original variable\n}\n\nint main() {\n    int a = 0;\n    set_value(a);      // a is still 0\n    set_value_ptr(&a); // a is now 100\n}\n```\n\nIn embedded systems, passing by pointer is essential for efficiency and for functions that need to return multiple values.","images":[{"url":"https://www.genspark.ai/api/files/s/OyaALdF5","alt":"Pass by value vs pointer comparison","caption":"Pass by Value vs Pass by Pointer"}]},
    {"title":"Pointers and Arrays","content":"Arrays and pointers are closely related in C. An array name decays to a pointer to its first element when passed to a function.\n\n```c\nvoid process_buffer(uint8_t *data, int length) {\n    for (int i = 0; i < length; i++) {\n        data[i] = data[i] * 2;\n    }\n}\n\nint main() {\n    uint8_t buffer[10] = {1, 2, 3, 4, 5};\n    process_buffer(buffer, 10);  // buffer decays to pointer\n}\n```\n\nThis is why functions receiving arrays typically also need a length parameter - the pointer alone does not carry size information.","images":[{"url":"https://www.genspark.ai/api/files/s/p8A1J3Lm","alt":"Array passed as pointer","caption":"Arrays Decay to Pointers"}]},
    {"title":"Pointers to Structures","content":"Structures are often passed by pointer to avoid copying large amounts of data. The arrow operator `->` is used to access members through a pointer.\n\n```c\ntypedef struct {\n    int16_t x;\n    int16_t y;\n    int16_t z;\n} AccelData;\n\nvoid read_accelerometer(AccelData *data) {\n    data->x = i2c_read_reg(ACCEL_ADDR, X_REG);\n    data->y = i2c_read_reg(ACCEL_ADDR, Y_REG);\n    data->z = i2c_read_reg(ACCEL_ADDR, Z_REG);\n}\n\nint main() {\n    AccelData accel;\n    read_accelerometer(&accel);\n}\n```\n\nPassing structures by pointer is standard practice in embedded code for both efficiency and to allow functions to populate data.","images":[{"url":"https://www.genspark.ai/api/files/s/gLkYh9Wv","alt":"Pointer to structure example","caption":"Passing Structures by Pointer"}]},
    {"title":"C++ References","content":"C++ references provide an alternative to pointers with cleaner syntax. A reference is an alias for another variable.\n\n```cpp\nvoid set_value(int &x) {\n    x = 100;  // Modifies original directly\n}\n\nint main() {\n    int a = 0;\n    set_value(a);  // a is now 100\n}\n```\n\nReferences cannot be null and cannot be reassigned, making them safer than pointers in many situations. However, pointers are still needed for dynamic memory and hardware addresses.","images":[{"url":"https://www.genspark.ai/api/files/s/Q7mNpRsT","alt":"C++ reference example","caption":"C++ References"}]},
    {"title":"Const Pointers","content":"The `const` keyword with pointers prevents accidental modification. There are two variations:\n\n```c\n// Pointer to const data - cannot modify data through pointer\nvoid print_buffer(const uint8_t *data, int len) {\n    // data[0] = 0;  // ERROR: cannot modify\n    for (int i = 0; i < len; i++) {\n        printf(\"%d \", data[i]);\n    }\n}\n\n// Const pointer - cannot change what pointer points to\nuint8_t * const fixed_ptr = buffer;\n// fixed_ptr = other;  // ERROR: cannot reassign pointer\n```\n\nUsing `const` correctly helps catch bugs at compile time and documents function intent.","images":[{"url":"https://www.genspark.ai/api/files/s/jH4kLmNp","alt":"Const pointer in function signature","caption":"Const Pointers for Safety"}]},
    {"title":"Pointers in Interrupts and Tasks","content":"When sharing data between interrupt handlers and main code, or between RTOS tasks, pointers often reference `volatile` variables.\n\n```c\nvolatile uint8_t button_pressed = 0;\n\nvoid IRAM_ATTR button_isr() {\n    button_pressed = 1;\n}\n\nvoid main_loop() {\n    if (button_pressed) {\n        button_pressed = 0;\n        handle_button();\n    }\n}\n```\n\nThe `volatile` keyword tells the compiler the variable can change unexpectedly, preventing optimizations that would cause incorrect behavior.","images":[{"url":"https://www.genspark.ai/api/files/s/rS5tUvWx","alt":"Volatile variable for ISR","caption":"Volatile Variables in Interrupts"}]}
  ]')
) WHERE id = 'lesson-t-pointers';

-- ============================================================================
-- LESSON: lesson-t-bits
-- Images mapped to sections:
-- page13_img1 -> "Masking to Extract Bits"
-- page14_img1 -> "Setting a Bit"
-- page14_img2 -> "Clearing a Bit"
-- page15_img1 -> "Toggling a Bit"
-- page15_img2 -> "Bit Field Manipulation"
-- page15_img3 -> "Combining and Extracting Nibbles" (combining)
-- page15_img4 -> "Combining and Extracting Nibbles" (extracting)
-- ============================================================================
UPDATE lessons SET content_json = json_set(
  json_remove(content_json, '$.images'),
  '$.sections',
  json('[
    {"title":"Why Bit Manipulation Matters","content":"In embedded systems, you frequently work at the bit level. Hardware registers, communication protocols, and sensor data often pack multiple values into single bytes or words.\n\nBit manipulation allows you to:\n- Read and write individual hardware register bits\n- Extract fields from packed data structures\n- Efficiently store boolean flags\n- Implement communication protocols\n\nMastering bitwise operations is essential for embedded firmware development."},
    {"title":"Bitwise Operators","content":"C provides six bitwise operators for manipulating individual bits:\n\n| Operator | Name | Description |\n|----------|------|-------------|\n| `&` | AND | 1 if both bits are 1 |\n| `\\|` | OR | 1 if either bit is 1 |\n| `^` | XOR | 1 if bits are different |\n| `~` | NOT | Inverts all bits |\n| `<<` | Left Shift | Shifts bits left |\n| `>>` | Right Shift | Shifts bits right |\n\n```c\nuint8_t a = 0b11001010;\nuint8_t b = 0b10101100;\n\na & b;   // 0b10001000 (AND)\na | b;   // 0b11101110 (OR)\na ^ b;   // 0b01100110 (XOR)\n~a;      // 0b00110101 (NOT)\na << 2;  // 0b00101000 (Left shift by 2)\na >> 2;  // 0b00110010 (Right shift by 2)\n```"},
    {"title":"Masking to Extract Bits","content":"A mask is a bit pattern used to isolate specific bits. AND with a mask extracts those bits, setting all others to zero.\n\n```c\n// Extract the lower nibble (bits 0-3)\nuint8_t value = 0x5A;  // 0101 1010\nuint8_t lower = value & 0x0F;  // 0000 1010 = 0x0A\n\n// Extract bits 4-6\nuint8_t bits_4_6 = (value >> 4) & 0x07;  // Shift then mask\n```\n\nMasking is commonly used to read BCD (Binary Coded Decimal) data from RTC chips and extract fields from sensor registers.","images":[{"url":"https://www.genspark.ai/api/files/s/yZ6aBcDe","alt":"BCD masking example","caption":"Masking to Extract Bits from BCD Data"}]},
    {"title":"Setting a Bit","content":"To set (turn on) a specific bit, OR with a mask that has 1 in that position.\n\n```c\n// Set bit 3 (counting from 0)\nuint8_t reg = 0b00000000;\nreg = reg | (1 << 3);  // 0b00001000\n\n// Shorthand\nreg |= (1 << 3);\n\n// Set multiple bits\nreg |= (1 << 5) | (1 << 2);  // Set bits 5 and 2\n```\n\nSetting bits is used to enable features in hardware registers or set flags in status variables.","images":[{"url":"https://www.genspark.ai/api/files/s/fG7hIjKl","alt":"Setting bit 3 example","caption":"Setting a Bit with OR"}]},
    {"title":"Clearing a Bit","content":"To clear (turn off) a specific bit, AND with a mask that has 0 in that position and 1s elsewhere.\n\n```c\n// Clear bit 2\nuint8_t reg = 0b11111111;\nreg = reg & ~(1 << 2);  // 0b11111011\n\n// Shorthand\nreg &= ~(1 << 2);\n\n// Clear multiple bits\nreg &= ~((1 << 5) | (1 << 2));  // Clear bits 5 and 2\n```\n\nClearing bits disables features or acknowledges interrupts in hardware registers.","images":[{"url":"https://www.genspark.ai/api/files/s/mN8oPqRs","alt":"Clearing bit 2 example","caption":"Clearing a Bit with AND NOT"}]},
    {"title":"Toggling a Bit","content":"To toggle (flip) a specific bit, XOR with a mask that has 1 in that position.\n\n```c\n// Toggle bit 4\nuint8_t reg = 0b00010000;\nreg = reg ^ (1 << 4);  // 0b00000000\nreg = reg ^ (1 << 4);  // 0b00010000 (back to original)\n\n// Shorthand\nreg ^= (1 << 4);\n```\n\nToggling is useful for blinking LEDs or alternating between two states.","images":[{"url":"https://www.genspark.ai/api/files/s/tU9vWxYz","alt":"Toggling a bit example","caption":"Toggling a Bit with XOR"}]},
    {"title":"Bit Field Manipulation","content":"A bit field is a group of adjacent bits that represent a single value. To modify a bit field, first clear it, then set the new value.\n\n```c\n// Bits 4-6 form a 3-bit field (values 0-7)\nuint8_t reg = 0b01110011;  // Field currently = 7\n\n// Clear the field (bits 4-6)\nreg &= ~(0x07 << 4);  // 0b00000011\n\n// Set new value (3) in the field\nreg |= (3 << 4);  // 0b00110011\n\n// Combined: clear and set in one step\nreg = (reg & ~(0x07 << 4)) | (new_value << 4);\n```\n\nBit fields are common in hardware configuration registers where different settings occupy different bit ranges.","images":[{"url":"https://www.genspark.ai/api/files/s/aB1cDeFg","alt":"Bit field manipulation","caption":"Clearing and Inserting a Bit Field"}]},
    {"title":"Combining and Extracting Nibbles","content":"A nibble is 4 bits (half a byte). Many protocols and formats pack two values into a single byte.\n\n```c\n// Combine two nibbles into one byte\nuint8_t high_nibble = 0x0A;  // 1010\nuint8_t low_nibble = 0x05;   // 0101\nuint8_t combined = (high_nibble << 4) | low_nibble;  // 0xA5\n\n// Extract nibbles from a byte\nuint8_t value = 0xA5;\nuint8_t high = (value >> 4) & 0x0F;  // 0x0A\nuint8_t low = value & 0x0F;          // 0x05\n```\n\nBCD (Binary Coded Decimal) data from RTC chips uses this format, storing tens digit in the upper nibble and ones digit in the lower nibble.","images":[{"url":"https://www.genspark.ai/api/files/s/hI2jKlMn","alt":"Combining nibbles","caption":"Combining Two Nibbles"},{"url":"https://www.genspark.ai/api/files/s/oP3qRsTu","alt":"Extracting nibbles","caption":"Extracting Nibbles from a Byte"}]}
  ]')
) WHERE id = 'lesson-t-bits';

-- ============================================================================
-- LESSON: lesson-t-i2c
-- Images mapped to sections:
-- page17_img1 -> "I2C Pin Configuration"
-- page18_img1 -> "I2C Initialization"
-- page19_img1 -> "Read and Write Functions"
-- ALSO: Add missing video URL
-- ============================================================================
UPDATE lessons SET content_json = json_set(
  json_remove(content_json, '$.images'),
  '$.video_url', 'https://www.youtube.com/watch?v=CAvawEcxoPU',
  '$.sections',
  json('[
    {"title":"Introduction to I2C","content":"I2C (Inter-Integrated Circuit) is a synchronous serial communication protocol widely used in embedded systems. It uses two wires:\n\n- **SDA** (Serial Data) - Bidirectional data line\n- **SCL** (Serial Clock) - Clock signal from master\n\nI2C supports multiple devices on the same bus, each with a unique 7-bit address. The T-Watch uses I2C to communicate with the accelerometer (BMA423), power management IC (AXP202), and real-time clock (PCF8563)."},
    {"title":"I2C Pin Configuration","content":"Before using I2C, you must define the pins and device addresses. On the T-Watch, I2C uses GPIO21 (SDA) and GPIO22 (SCL).\n\n```c\n#define I2C_SDA_PIN     21\n#define I2C_SCL_PIN     22\n#define I2C_FREQUENCY   400000  // 400kHz Fast Mode\n\n// Device addresses\n#define AXP202_ADDR     0x35\n#define PCF8563_ADDR    0x51\n#define BMA423_ADDR     0x18\n```\n\nAlways verify pin assignments and addresses against the hardware schematic and datasheets.","images":[{"url":"https://www.genspark.ai/api/files/s/vW4xYzAb","alt":"I2C configuration defines","caption":"I2C Pin and Address Configuration"}]},
    {"title":"I2C Initialization","content":"Initialize the I2C peripheral before communicating with devices. The ESP32 Arduino framework uses the Wire library.\n\n```cpp\n#include <Wire.h>\n\nvoid i2c_init(void) {\n    Wire.begin(I2C_SDA_PIN, I2C_SCL_PIN, I2C_FREQUENCY);\n}\n```\n\nFor low-level control, you can use the ESP-IDF I2C driver:\n\n```c\ni2c_config_t conf = {\n    .mode = I2C_MODE_MASTER,\n    .sda_io_num = I2C_SDA_PIN,\n    .scl_io_num = I2C_SCL_PIN,\n    .sda_pullup_en = GPIO_PULLUP_ENABLE,\n    .scl_pullup_en = GPIO_PULLUP_ENABLE,\n    .master.clk_speed = I2C_FREQUENCY\n};\ni2c_param_config(I2C_NUM_0, &conf);\ni2c_driver_install(I2C_NUM_0, I2C_MODE_MASTER, 0, 0, 0);\n```","images":[{"url":"https://www.genspark.ai/api/files/s/cD5eFgHi","alt":"I2C initialization code","caption":"I2C Master Initialization"}]},
    {"title":"Driver Architecture","content":"A well-designed I2C driver separates low-level communication from device-specific logic:\n\n**Low-level functions:**\n- `i2c_write_reg()` - Write a value to a register\n- `i2c_read_reg()` - Read a value from a register\n- `i2c_read_bytes()` - Read multiple bytes\n\n**Device-specific functions:**\n- `accel_init()`, `accel_read_xyz()`\n- `rtc_get_time()`, `rtc_set_time()`\n- `pmu_get_battery()`, `pmu_enable_output()`\n\nThis separation makes code reusable and easier to maintain."},
    {"title":"Read and Write Functions","content":"Generic I2C read/write functions form the foundation of your driver:\n\n```c\nbool i2c_write_reg(uint8_t addr, uint8_t reg, uint8_t value) {\n    Wire.beginTransmission(addr);\n    Wire.write(reg);\n    Wire.write(value);\n    return Wire.endTransmission() == 0;\n}\n\nuint8_t i2c_read_reg(uint8_t addr, uint8_t reg) {\n    Wire.beginTransmission(addr);\n    Wire.write(reg);\n    Wire.endTransmission(false);  // Repeated start\n    Wire.requestFrom(addr, (uint8_t)1);\n    return Wire.read();\n}\n\nbool i2c_read_bytes(uint8_t addr, uint8_t reg, uint8_t *data, uint8_t len) {\n    Wire.beginTransmission(addr);\n    Wire.write(reg);\n    Wire.endTransmission(false);\n    Wire.requestFrom(addr, len);\n    for (int i = 0; i < len && Wire.available(); i++) {\n        data[i] = Wire.read();\n    }\n    return true;\n}\n```","images":[{"url":"https://www.genspark.ai/api/files/s/jK6lMnOp","alt":"I2C read write functions","caption":"I2C Driver Read/Write Functions"}]},
    {"title":"Device-Specific Functions","content":"Build device-specific functions on top of the generic I2C layer:\n\n```c\n// RTC: Read current time\nvoid rtc_get_time(uint8_t *hour, uint8_t *min, uint8_t *sec) {\n    uint8_t data[3];\n    i2c_read_bytes(PCF8563_ADDR, 0x02, data, 3);\n    *sec = bcd_to_dec(data[0] & 0x7F);\n    *min = bcd_to_dec(data[1] & 0x7F);\n    *hour = bcd_to_dec(data[2] & 0x3F);\n}\n\n// Accelerometer: Read XYZ\nvoid accel_read_xyz(int16_t *x, int16_t *y, int16_t *z) {\n    uint8_t data[6];\n    i2c_read_bytes(BMA423_ADDR, 0x12, data, 6);\n    *x = (int16_t)((data[1] << 8) | data[0]) >> 4;\n    *y = (int16_t)((data[3] << 8) | data[2]) >> 4;\n    *z = (int16_t)((data[5] << 8) | data[4]) >> 4;\n}\n```\n\nRefer to device datasheets for register addresses and data formats."},
    {"title":"Error Handling","content":"Always check for communication errors and implement appropriate recovery:\n\n```c\nbool i2c_write_reg_safe(uint8_t addr, uint8_t reg, uint8_t value) {\n    for (int retry = 0; retry < 3; retry++) {\n        if (i2c_write_reg(addr, reg, value)) {\n            return true;\n        }\n        delay(1);  // Brief delay before retry\n    }\n    Serial.printf(\"I2C write failed: addr=0x%02X reg=0x%02X\\n\", addr, reg);\n    return false;\n}\n```\n\nCommon I2C issues include:\n- Wrong device address\n- Device not powered or in sleep mode\n- Bus contention from multiple masters\n- Missing pull-up resistors"}
  ]')
) WHERE id = 'lesson-t-i2c';

-- ============================================================================
-- LESSON: lesson-t-oop
-- Images mapped to sections:
-- page21_img1 -> "Classes and Objects" (Basic Class Declaration)
-- page21_img2 -> "Classes and Objects" (Creating Multiple Objects)
-- page22_img1 -> "Encapsulation and Access Control"
-- page23_img1 -> "Encapsulation for Hardware"
-- page24_img1 -> "Constructors"
-- page25_img1 -> "Header and Source Files for Classes" (header)
-- page25_img2 -> "Header and Source Files for Classes" (source)
-- page26_img1 -> "Using Classes in Main Code"
-- ============================================================================
UPDATE lessons SET content_json = json_set(
  json_remove(content_json, '$.images'),
  '$.sections',
  json('[
    {"title":"Introduction to OOP in Embedded Systems","content":"Object-Oriented Programming (OOP) in C++ helps organize complex embedded projects. While C is sufficient for many embedded tasks, C++ classes provide:\n\n- **Encapsulation** - Bundle data and functions together\n- **Abstraction** - Hide implementation details\n- **Modularity** - Self-contained, reusable components\n\nThe T-Watch project uses OOP to create clean interfaces for hardware peripherals like motors, LEDs, and sensors."},
    {"title":"Classes and Objects","content":"A class is a blueprint that defines data (member variables) and behavior (member functions). An object is an instance of a class.\n\n```cpp\nclass Motor {\npublic:\n    int speed;\n    \n    void setSpeed(int s) {\n        speed = s;\n    }\n    \n    void stop() {\n        speed = 0;\n    }\n};\n\n// Creating objects\nMotor leftMotor;\nMotor rightMotor;\n\nleftMotor.setSpeed(100);\nrightMotor.setSpeed(50);\n```\n\nEach object has its own copy of member variables but shares the same member functions.","images":[{"url":"https://www.genspark.ai/api/files/s/qR7sTuVw","alt":"Motor class declaration","caption":"Basic Class Declaration"},{"url":"https://www.genspark.ai/api/files/s/xY8zAbCd","alt":"Creating class instances","caption":"Creating Multiple Objects"}]},
    {"title":"Encapsulation and Access Control","content":"Encapsulation hides internal data and provides controlled access through public methods. Use `private` for internal data and `public` for the interface.\n\n```cpp\nclass Motor {\nprivate:\n    int speed;  // Hidden from outside\n    \npublic:\n    void setSpeed(int s) {\n        if (s >= 0 && s <= 255) {  // Validation\n            speed = s;\n        }\n    }\n    \n    int getSpeed() {\n        return speed;\n    }\n};\n```\n\nThis prevents direct access to `speed` and ensures values are always valid.","images":[{"url":"https://www.genspark.ai/api/files/s/eF9gHiJk","alt":"Encapsulation with state variable","caption":"Encapsulation with Setter Method"}]},
    {"title":"Encapsulation for Hardware","content":"OOP is particularly useful for wrapping hardware peripherals. Each class manages its own pins and state.\n\n```cpp\nclass LED {\nprivate:\n    int pin;\n    bool state;\n    \npublic:\n    LED(int p) : pin(p), state(false) {\n        pinMode(pin, OUTPUT);\n    }\n    \n    void on() {\n        digitalWrite(pin, HIGH);\n        state = true;\n    }\n    \n    void off() {\n        digitalWrite(pin, LOW);\n        state = false;\n    }\n    \n    void toggle() {\n        state ? off() : on();\n    }\n};\n\n// Usage\nLED statusLed(13);\nstatusLed.on();\n```","images":[{"url":"https://www.genspark.ai/api/files/s/lM0nOpQr","alt":"LED class example","caption":"Hardware Encapsulation - LED Class"}]},
    {"title":"Constructors","content":"A constructor is a special function that runs when an object is created. Use it to initialize member variables and configure hardware.\n\n```cpp\nclass Sensor {\nprivate:\n    int i2c_addr;\n    uint8_t buffer[6];\n    \npublic:\n    // Constructor with initialization list\n    Sensor(int addr) : i2c_addr(addr) {\n        // Initialize hardware\n        Wire.begin();\n        configure();\n    }\n    \n    void configure() {\n        i2c_write_reg(i2c_addr, CONFIG_REG, 0x80);\n    }\n};\n\n// Object created and configured automatically\nSensor accel(0x18);\n```\n\nThe initialization list (`: i2c_addr(addr)`) is the preferred way to initialize members.","images":[{"url":"https://www.genspark.ai/api/files/s/sT1uVwXy","alt":"Sensor class with constructor","caption":"Class with Constructor"}]},
    {"title":"Header and Source Files for Classes","content":"Like C modules, C++ classes should be split into header (.h) and source (.cpp) files.\n\n**motor.h:**\n```cpp\n#ifndef MOTOR_H\n#define MOTOR_H\n\nclass Motor {\nprivate:\n    int pwmPin;\n    int dirPin;\n    int speed;\n    \npublic:\n    Motor(int pwm, int dir);\n    void setSpeed(int s);\n    void stop();\n    int getSpeed();\n};\n\n#endif\n```\n\n**motor.cpp:**\n```cpp\n#include \"motor.h\"\n#include <Arduino.h>\n\nMotor::Motor(int pwm, int dir) : pwmPin(pwm), dirPin(dir), speed(0) {\n    pinMode(pwmPin, OUTPUT);\n    pinMode(dirPin, OUTPUT);\n}\n\nvoid Motor::setSpeed(int s) {\n    speed = constrain(s, -255, 255);\n    digitalWrite(dirPin, speed >= 0 ? HIGH : LOW);\n    analogWrite(pwmPin, abs(speed));\n}\n\nvoid Motor::stop() {\n    setSpeed(0);\n}\n\nint Motor::getSpeed() {\n    return speed;\n}\n```","images":[{"url":"https://www.genspark.ai/api/files/s/zA2bCdEf","alt":"Motor header file","caption":"Motor Class Header (motor.h)"},{"url":"https://www.genspark.ai/api/files/s/gH3iJkLm","alt":"Motor source file","caption":"Motor Class Implementation (motor.cpp)"}]},
    {"title":"Using Classes in Main Code","content":"Include the header file and create objects as needed:\n\n```cpp\n#include \"motor.h\"\n#include \"led.h\"\n#include \"sensor.h\"\n\nMotor leftMotor(5, 6);\nMotor rightMotor(9, 10);\nLED statusLed(13);\nSensor accel(0x18);\n\nvoid setup() {\n    Serial.begin(115200);\n    statusLed.on();\n}\n\nvoid loop() {\n    int16_t x, y, z;\n    accel.read(&x, &y, &z);\n    \n    // Use accelerometer to control motors\n    leftMotor.setSpeed(map(x, -2000, 2000, -255, 255));\n    rightMotor.setSpeed(map(y, -2000, 2000, -255, 255));\n    \n    delay(50);\n}\n```\n\nOOP makes the main code clean and focused on high-level logic rather than low-level details.","images":[{"url":"https://www.genspark.ai/api/files/s/nO4pQrSt","alt":"Using motor class in main","caption":"Using the Motor Class"}]}
  ]')
) WHERE id = 'lesson-t-oop';

-- ============================================================================
-- LESSON: lesson-t-rtos
-- Images mapped to sections:
-- page27_img1 -> "Tasks" (Task Function Structure)
-- page27_img2 -> "Creating Tasks"
-- page28_img1 -> "Mutexes for Shared Resources" (Using Mutex in a Task)
-- page29_img1 -> "Mutexes for Shared Resources" (Mutex Task Display Example) - MISSING, adding now
-- page29_img2 -> "Multiple Tasks with Mutex"
-- ============================================================================
UPDATE lessons SET content_json = json_set(
  json_remove(content_json, '$.images'),
  '$.sections',
  json('[
    {"title":"Introduction to RTOS","content":"A Real-Time Operating System (RTOS) enables concurrent execution of multiple tasks. FreeRTOS, which runs on the ESP32, provides:\n\n- **Task scheduling** - Multiple functions run \"simultaneously\"\n- **Synchronization** - Mutexes, semaphores, queues\n- **Timing** - Precise delays and timeouts\n- **Memory management** - Dynamic allocation for tasks\n\nThe T-Watch uses FreeRTOS to handle display updates, sensor reading, and user input concurrently."},
    {"title":"Tasks","content":"A task is a function that runs independently. Each task has its own stack and runs in an infinite loop.\n\n```c\nvoid sensorTask(void *parameter) {\n    while (1) {\n        // Read sensor data\n        int16_t x = accel_read_x();\n        int16_t y = accel_read_y();\n        \n        // Process data\n        update_step_count(x, y);\n        \n        // Delay before next iteration\n        vTaskDelay(pdMS_TO_TICKS(100));\n    }\n}\n```\n\nThe `vTaskDelay()` function yields CPU time to other tasks, allowing the scheduler to run them.","images":[{"url":"https://www.genspark.ai/api/files/s/uV5wXyZa","alt":"Basic task function","caption":"Task Function Structure"}]},
    {"title":"Creating Tasks","content":"Use `xTaskCreate()` or `xTaskCreatePinnedToCore()` to create tasks:\n\n```c\nvoid setup() {\n    xTaskCreatePinnedToCore(\n        sensorTask,       // Task function\n        \"SensorTask\",     // Task name (for debugging)\n        4096,             // Stack size in bytes\n        NULL,             // Parameter passed to task\n        1,                // Priority (higher = more important)\n        NULL,             // Task handle (optional)\n        0                 // Core to run on (0 or 1)\n    );\n    \n    xTaskCreatePinnedToCore(\n        displayTask,\n        \"DisplayTask\",\n        8192,\n        NULL,\n        2,                // Higher priority\n        NULL,\n        1                 // Different core\n    );\n}\n```\n\nThe ESP32 has two cores, so you can pin tasks to specific cores for better performance.","images":[{"url":"https://www.genspark.ai/api/files/s/bC6dEfGh","alt":"xTaskCreate example","caption":"Creating a Task with xTaskCreate"}]},
    {"title":"Task Delays","content":"Use `vTaskDelay()` instead of `delay()` in RTOS tasks. This allows other tasks to run during the wait.\n\n```c\n// Convert milliseconds to ticks\nvTaskDelay(pdMS_TO_TICKS(100));  // 100ms delay\n\n// Direct tick count (if you know tick rate)\nvTaskDelay(100);  // 100 ticks\n```\n\nNever use blocking `delay()` in RTOS tasks - it prevents the scheduler from running other tasks."},
    {"title":"Mutexes for Shared Resources","content":"When multiple tasks access the same resource (display, serial port, shared variable), use a mutex to prevent conflicts.\n\n```c\nSemaphoreHandle_t displayMutex;\n\nvoid setup() {\n    displayMutex = xSemaphoreCreateMutex();\n}\n\nvoid displayTask(void *param) {\n    while (1) {\n        if (xSemaphoreTake(displayMutex, portMAX_DELAY)) {\n            // Safe to use display\n            tft.fillScreen(TFT_BLACK);\n            tft.drawString(\"Hello\", 10, 10);\n            \n            xSemaphoreGive(displayMutex);  // Release mutex\n        }\n        vTaskDelay(pdMS_TO_TICKS(50));\n    }\n}\n```\n\nOnly one task can hold the mutex at a time, preventing display corruption from concurrent writes.","images":[{"url":"https://www.genspark.ai/api/files/s/iJ7kLmNo","alt":"Task with mutex","caption":"Using Mutex in a Task"},{"url":"https://www.genspark.ai/api/files/s/pQ8rStUv","alt":"Mutex task display","caption":"Mutex Task Display Example"}]},
    {"title":"Multiple Tasks with Mutex","content":"Multiple tasks can share a resource safely using the same mutex:\n\n```c\nvoid timeTask(void *param) {\n    while (1) {\n        if (xSemaphoreTake(displayMutex, pdMS_TO_TICKS(100))) {\n            display_time();\n            xSemaphoreGive(displayMutex);\n        }\n        vTaskDelay(pdMS_TO_TICKS(1000));\n    }\n}\n\nvoid notifyTask(void *param) {\n    while (1) {\n        if (has_notification()) {\n            if (xSemaphoreTake(displayMutex, pdMS_TO_TICKS(100))) {\n                display_notification();\n                xSemaphoreGive(displayMutex);\n            }\n        }\n        vTaskDelay(pdMS_TO_TICKS(100));\n    }\n}\n```\n\nThe timeout parameter (`pdMS_TO_TICKS(100)`) prevents tasks from waiting forever if another task holds the mutex too long.","images":[{"url":"https://www.genspark.ai/api/files/s/wX9yZaBc","alt":"Multiple tasks with mutex","caption":"Multiple Tasks Sharing a Resource"}]}
  ]')
) WHERE id = 'lesson-t-rtos';

-- ============================================================================
-- LESSON: lesson-t-static-volatile
-- Images mapped to sections:
-- page31_img1 -> "Static Variables"
-- page31_img2 -> "Volatile Variables"
-- page32_img1 -> "Combining Static and Volatile"
-- ============================================================================
UPDATE lessons SET content_json = json_set(
  json_remove(content_json, '$.images'),
  '$.sections',
  json('[
    {"title":"Introduction","content":"The `static` and `volatile` keywords modify how variables are stored and accessed. Understanding these modifiers is essential for embedded programming where you deal with interrupts, shared memory, and persistent state."},
    {"title":"Static Variables","content":"A `static` local variable retains its value between function calls, unlike regular local variables which are reinitialized each time.\n\n```c\nvoid count_calls() {\n    static int count = 0;  // Initialized once\n    count++;\n    printf(\"Called %d times\\n\", count);\n}\n\n// First call: \"Called 1 times\"\n// Second call: \"Called 2 times\"\n// Third call: \"Called 3 times\"\n```\n\nStatic variables are useful for maintaining state without using global variables, keeping the state encapsulated within the function.","images":[{"url":"https://www.genspark.ai/api/files/s/dE0fGhIj","alt":"Static variable example","caption":"Static Variable Persists Between Calls"}]},
    {"title":"Static Functions","content":"A `static` function is only visible within its source file, preventing name conflicts with other files.\n\n```c\n// In motor.c\nstatic void configure_pwm() {\n    // Private helper function\n}\n\nvoid motor_init() {\n    configure_pwm();  // OK: same file\n}\n\n// In main.c\nconfigure_pwm();  // ERROR: not visible\n```\n\nUse static for helper functions that should not be called from other modules."},
    {"title":"Volatile Variables","content":"The `volatile` keyword tells the compiler that a variable can change unexpectedly (by hardware or interrupts). Without it, the compiler might optimize away reads, causing bugs.\n\n```c\nvolatile bool button_pressed = false;\n\nvoid IRAM_ATTR button_isr() {\n    button_pressed = true;  // Set in interrupt\n}\n\nvoid loop() {\n    if (button_pressed) {  // Compiler must read actual value\n        button_pressed = false;\n        handle_press();\n    }\n}\n```\n\nWithout `volatile`, the compiler might assume `button_pressed` never changes in `loop()` and optimize the check away.","images":[{"url":"https://www.genspark.ai/api/files/s/kL1mNoP1","alt":"Volatile with ISR","caption":"Volatile Variable for ISR Communication"}]},
    {"title":"Combining Static and Volatile","content":"Sometimes you need both: persistence (static) and interrupt-safety (volatile).\n\n```c\nvoid check_button() {\n    static volatile uint32_t last_press = 0;\n    uint32_t now = millis();\n    \n    if (button_pin_low() && (now - last_press > 200)) {\n        last_press = now;  // Debounce timing\n        handle_press();\n    }\n}\n```\n\n`static` keeps the value between calls, `volatile` ensures the compiler does not optimize away reads if this function could be interrupted.","images":[{"url":"https://www.genspark.ai/api/files/s/rS2tUvWx","alt":"Static volatile combined","caption":"Combining Static and Volatile"}]},
    {"title":"When to Use Each","content":"**Use `static` for:**\n- Local variables that must persist between calls\n- Functions that should be private to a file\n- Module-level variables shared within a file\n\n**Use `volatile` for:**\n- Variables modified by interrupt handlers\n- Hardware registers\n- Variables shared between RTOS tasks\n- Memory-mapped I/O\n\n**Use both for:**\n- Persistent variables accessed by interrupts\n- Debounce timers in interrupt-driven code"}
  ]')
) WHERE id = 'lesson-t-static-volatile';

-- ============================================================================
-- LESSON: lesson-t-timing
-- Images mapped to sections:
-- page33_img1 -> "Blocking Delays"
-- page33_img2 -> "Non-Blocking Timing"
-- page34_img1 -> "RTOS Task Delays"
-- page34_img2 -> "Hardware Timers"
-- page35_img1 -> "Debouncing"
-- ============================================================================
UPDATE lessons SET content_json = json_set(
  json_remove(content_json, '$.images'),
  '$.sections',
  json('[
    {"title":"Introduction to Timing","content":"Timing control is fundamental to embedded systems. You need precise timing for:\n\n- Periodic sensor readings\n- Display refresh rates\n- Communication protocols\n- User input debouncing\n- Power management\n\nDifferent approaches offer trade-offs between simplicity, precision, and CPU efficiency."},
    {"title":"Blocking Delays","content":"The simplest approach uses `delay()`, which blocks execution for a specified time.\n\n```c\nvoid loop() {\n    read_sensor();\n    delay(100);  // Wait 100ms\n    update_display();\n    delay(50);   // Wait 50ms\n}\n```\n\n**Pros:** Simple to understand and use\n**Cons:** CPU does nothing during delay; cannot respond to events; accumulates timing drift\n\nAvoid blocking delays in production code except for initialization sequences.","images":[{"url":"https://www.genspark.ai/api/files/s/yZ3aBcDe","alt":"Blocking delay example","caption":"Blocking Delay - Simple but Inefficient"}]},
    {"title":"Non-Blocking Timing","content":"Use `millis()` to track elapsed time without blocking. This allows the CPU to do other work.\n\n```c\nuint32_t lastSensorRead = 0;\nuint32_t lastDisplayUpdate = 0;\n\nvoid loop() {\n    uint32_t now = millis();\n    \n    if (now - lastSensorRead >= 100) {\n        lastSensorRead = now;\n        read_sensor();\n    }\n    \n    if (now - lastDisplayUpdate >= 50) {\n        lastDisplayUpdate = now;\n        update_display();\n    }\n    \n    // Can do other work here\n    check_buttons();\n}\n```\n\nThis pattern enables responsive systems that handle multiple tasks concurrently.","images":[{"url":"https://www.genspark.ai/api/files/s/fG4hIjKl","alt":"Non-blocking timing","caption":"Non-Blocking Timing with millis()"}]},
    {"title":"RTOS Task Delays","content":"In FreeRTOS, use `vTaskDelay()` instead of `delay()`. This yields CPU time to other tasks.\n\n```c\nvoid sensorTask(void *param) {\n    TickType_t lastWakeTime = xTaskGetTickCount();\n    \n    while (1) {\n        read_sensor();\n        \n        // Delay until next period (more precise)\n        vTaskDelayUntil(&lastWakeTime, pdMS_TO_TICKS(100));\n    }\n}\n```\n\n`vTaskDelayUntil()` compensates for task execution time, maintaining precise periods.","images":[{"url":"https://www.genspark.ai/api/files/s/mN5oPqRs","alt":"RTOS task delay","caption":"RTOS Task Delay with vTaskDelay()"}]},
    {"title":"Hardware Timers","content":"For precise timing or generating signals, use hardware timers. They run independently of CPU execution.\n\n```c\nhw_timer_t *timer = NULL;\nvolatile bool timer_fired = false;\n\nvoid IRAM_ATTR onTimer() {\n    timer_fired = true;\n}\n\nvoid setup() {\n    // Configure timer: 80MHz / 80 = 1MHz (1us resolution)\n    timer = timerBegin(0, 80, true);\n    timerAttachInterrupt(timer, &onTimer, true);\n    timerAlarmWrite(timer, 1000, true);  // 1000us = 1ms\n    timerAlarmEnable(timer);\n}\n\nvoid loop() {\n    if (timer_fired) {\n        timer_fired = false;\n        // Handle timer event\n    }\n}\n```\n\nHardware timers are essential for PWM, precise measurements, and time-critical operations.","images":[{"url":"https://www.genspark.ai/api/files/s/tU6vWxYz","alt":"Hardware timer example","caption":"Hardware Timer Interrupt"}]},
    {"title":"Debouncing","content":"Mechanical buttons bounce, causing multiple triggers. Debouncing filters out these false readings.\n\n```c\n#define DEBOUNCE_MS 50\n\nuint32_t lastDebounceTime = 0;\nbool lastButtonState = HIGH;\nbool buttonState = HIGH;\n\nvoid check_button() {\n    bool reading = digitalRead(BUTTON_PIN);\n    \n    if (reading != lastButtonState) {\n        lastDebounceTime = millis();\n    }\n    \n    if ((millis() - lastDebounceTime) > DEBOUNCE_MS) {\n        if (reading != buttonState) {\n            buttonState = reading;\n            if (buttonState == LOW) {\n                handle_press();\n            }\n        }\n    }\n    \n    lastButtonState = reading;\n}\n```\n\nThe touch screen on the T-Watch also benefits from debouncing to prevent accidental multiple taps.","images":[{"url":"https://www.genspark.ai/api/files/s/aB7cDeFg","alt":"Debounce timing","caption":"Debouncing Touch Input"}]}
  ]')
) WHERE id = 'lesson-t-timing';

-- ============================================================================
-- LESSON: lesson-t-fsm
-- Images: page38_img1 -> "Implementing an FSM"
-- ============================================================================
UPDATE lessons SET content_json = json_set(
  json_remove(content_json, '$.images'),
  '$.sections',
  json('[
    {"title":"Introduction to Finite State Machines","content":"A Finite State Machine (FSM) is a design pattern that organizes code around discrete states and transitions. FSMs are ideal for:\n\n- Menu navigation\n- Screen management\n- Device modes (idle, active, sleep)\n- Protocol handling\n- User interaction flows\n\nThe T-Watch uses an FSM to manage different screens: home, time, accelerometer, settings, etc."},
    {"title":"FSM Components","content":"Every FSM has three core components:\n\n**States:** The distinct modes your system can be in\n```c\ntypedef enum {\n    STATE_HOME,\n    STATE_TIME,\n    STATE_ACCEL,\n    STATE_SETTINGS,\n    STATE_SLEEP\n} AppState;\n```\n\n**Events:** Inputs that trigger transitions\n```c\ntypedef enum {\n    EVENT_TOUCH,\n    EVENT_BUTTON,\n    EVENT_TIMEOUT,\n    EVENT_WAKE\n} AppEvent;\n```\n\n**Transitions:** Rules for moving between states based on events"},
    {"title":"Implementing an FSM","content":"A switch statement is the simplest FSM implementation:\n\n```c\nAppState currentState = STATE_HOME;\n\nvoid handle_event(AppEvent event) {\n    switch (currentState) {\n        case STATE_HOME:\n            if (event == EVENT_TOUCH) {\n                currentState = STATE_TIME;\n                enter_time_screen();\n            } else if (event == EVENT_TIMEOUT) {\n                currentState = STATE_SLEEP;\n                enter_sleep();\n            }\n            break;\n            \n        case STATE_TIME:\n            if (event == EVENT_TOUCH) {\n                currentState = STATE_ACCEL;\n                enter_accel_screen();\n            } else if (event == EVENT_BUTTON) {\n                currentState = STATE_HOME;\n                enter_home_screen();\n            }\n            break;\n            \n        case STATE_ACCEL:\n            if (event == EVENT_TOUCH) {\n                currentState = STATE_SETTINGS;\n                enter_settings_screen();\n            }\n            break;\n            \n        // ... more states\n    }\n}\n```\n\nEach state handles its own transitions, making the logic clear and maintainable.","images":[{"url":"https://www.genspark.ai/api/files/s/hI8jKlMn","alt":"FSM implementation with switch statement","caption":"FSM Implementation for Screen Navigation"}]},
    {"title":"Benefits of FSM Design","content":"FSMs provide several advantages:\n\n**Clarity:** The system is always in exactly one known state\n**Debugging:** Easy to trace what state caused a bug\n**Extensibility:** Add new states without breaking existing ones\n**Testing:** Test each state and transition independently\n\nFor complex systems, consider using a state table or state pattern instead of a switch statement."},
    {"title":"State Transitions","content":"Good FSM design includes entry and exit actions:\n\n```c\nvoid transition_to(AppState newState) {\n    // Exit current state\n    switch (currentState) {\n        case STATE_HOME:\n            save_home_position();\n            break;\n        case STATE_TIME:\n            stop_time_update();\n            break;\n    }\n    \n    // Enter new state\n    currentState = newState;\n    switch (newState) {\n        case STATE_HOME:\n            draw_home_screen();\n            start_idle_timer();\n            break;\n        case STATE_TIME:\n            draw_time_screen();\n            start_time_update();\n            break;\n    }\n}\n```\n\nThis ensures resources are properly initialized and cleaned up during transitions."}
  ]')
) WHERE id = 'lesson-t-fsm';

-- ============================================================================
-- LESSON: lesson-t-networking
-- Images mapped to sections:
-- page39_img1 -> "Connecting to WiFi"
-- page40_img1 -> "NTP Time Synchronization"
-- ============================================================================
UPDATE lessons SET content_json = json_set(
  json_remove(content_json, '$.images'),
  '$.sections',
  json('[
    {"title":"Introduction to WiFi on ESP32","content":"The ESP32 has built-in WiFi capabilities that enable:\n\n- **NTP time synchronization** - Get accurate time from the internet\n- **Cloud data upload** - Send sensor data to servers\n- **Notifications** - Receive alerts and messages\n- **OTA updates** - Update firmware wirelessly\n\nThe T-Watch uses WiFi primarily for time synchronization with NTP servers."},
    {"title":"Connecting to WiFi","content":"Use the WiFi library to connect to a network:\n\n```cpp\n#include <WiFi.h>\n\nconst char* ssid = \"YourNetworkName\";\nconst char* password = \"YourPassword\";\n\nvoid wifi_connect() {\n    WiFi.begin(ssid, password);\n    \n    Serial.print(\"Connecting to WiFi\");\n    while (WiFi.status() != WL_CONNECTED) {\n        delay(500);\n        Serial.print(\".\");\n    }\n    \n    Serial.println();\n    Serial.print(\"Connected! IP: \");\n    Serial.println(WiFi.localIP());\n}\n```\n\nAlways include a timeout to avoid hanging if the network is unavailable.","images":[{"url":"https://www.genspark.ai/api/files/s/52YAFb3q","alt":"WiFi connection code","caption":"Basic WiFi Connection"}]},
    {"title":"WiFi Status Checking","content":"Check WiFi status before making network requests:\n\n```cpp\nif (WiFi.status() == WL_CONNECTED) {\n    // Safe to make network requests\n    sync_time();\n} else {\n    Serial.println(\"WiFi not connected\");\n}\n```\n\n**WiFi status constants:**\n- `WL_CONNECTED` - Successfully connected\n- `WL_DISCONNECTED` - Not connected\n- `WL_CONNECT_FAILED` - Connection attempt failed\n- `WL_NO_SSID_AVAIL` - Network not found"},
    {"title":"NTP Time Synchronization","content":"Network Time Protocol (NTP) provides accurate time from internet servers:\n\n```cpp\n#include <time.h>\n\nvoid sync_ntp_time() {\n    configTime(0, 0, \"pool.ntp.org\", \"time.nist.gov\");\n    \n    Serial.print(\"Waiting for NTP sync\");\n    time_t now = time(nullptr);\n    while (now < 1000000000) {\n        delay(500);\n        Serial.print(\".\");\n        now = time(nullptr);\n    }\n    Serial.println(\" Done!\");\n    \n    // Store in hardware RTC\n    struct tm timeinfo;\n    localtime_r(&now, &timeinfo);\n    rtc_set_time(timeinfo.tm_hour, timeinfo.tm_min, timeinfo.tm_sec);\n    rtc_set_date(timeinfo.tm_year + 1900, timeinfo.tm_mon + 1, timeinfo.tm_mday);\n}\n```\n\nAfter NTP sync, store the time in the hardware RTC so it persists without WiFi.","images":[{"url":"https://www.genspark.ai/api/files/s/S6mWhW98","alt":"NTP time sync example","caption":"NTP Time Synchronization"}]},
    {"title":"Power Considerations","content":"WiFi consumes significant power. For a battery-powered watch:\n\n**Best practices:**\n- Only enable WiFi when needed\n- Disconnect and turn off WiFi after use\n- Use periodic sync (once per day) rather than continuous connection\n- Consider light-sleep between operations\n\n```cpp\nvoid wifi_off() {\n    WiFi.disconnect(true);\n    WiFi.mode(WIFI_OFF);\n}\n\nvoid daily_sync() {\n    wifi_connect();\n    sync_ntp_time();\n    wifi_off();  // Save power\n}\n```\n\nWith proper power management, battery life can be significantly extended."}
  ]')
) WHERE id = 'lesson-t-networking';
