-- Migration 0016: Complete Reorganization of Smartwatch Course
-- Restructure into 3 main modules: Overview, Training Material, Project Modules
-- CRITICAL: Preserve all text exactly as specified

-- ============================================================================
-- STEP 1: Update Module Structure (3 main modules)
-- ============================================================================

-- Delete old modules and create new structure
DELETE FROM course_modules WHERE course_id = 'smartwatch-course';

INSERT INTO course_modules (id, course_id, title, description, order_index, is_published) VALUES
  ('mod-overview', 'smartwatch-course', 'Overview', 'Introduction and setup for the smartwatch project', 0, 1),
  ('mod-training', 'smartwatch-course', 'Training Material', 'Technical training materials covering embedded systems concepts', 1, 1),
  ('mod-projects', 'smartwatch-course', 'Project Modules', 'Hands-on project implementation modules', 2, 1);

-- ============================================================================
-- STEP 2: Delete all existing lessons for smartwatch course
-- ============================================================================
DELETE FROM lessons WHERE course_id = 'smartwatch-course';

-- ============================================================================
-- STEP 3: MODULE 1 - OVERVIEW (5 sub-modules)
-- ============================================================================

-- 3.1 Introduction
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-overview-intro', 'mod-overview', 'smartwatch-course', 'Introduction', 'Introduction to the smartwatch project', 'text', 0, 1,
'{"sections":[{"title":"Introduction","content":"In this program you will design and implement a fully functioning smartwatch by combining low level driver development, embedded systems programming, and system-level integration.\n\nYou will work on the **LilyGo T-Watch 2020 V3**, a real commercial smartwatch platform, and write production-style firmware entirely in C and C++: the same languages used in industry for resource-constrained embedded systems.\n\n- **C** is used for low-level hardware control and communication\n- **C++** enables modular design, abstraction, and higher-level application logic\n\nThroughout the program you will build your system incrementally using provided training materials, reference implementations, and targeted code examples. These resources are designed to support you without removing the need for engineering decision making.\n\nIf you need help, email **support@shortcct.com** with your specific questions and a zip file including your project directory. Remember, virtual support is available for **3 months** after your product delivery date."}]}');

-- 3.2 Recommended Background
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-overview-background', 'mod-overview', 'smartwatch-course', 'Recommended Background', 'Prerequisites and recommended knowledge', 'text', 1, 1,
'{"sections":[{"title":"Recommended Background","content":"This project is designed for students who want hands-on embedded firmware experience. You do not need a lot of experience, but some foundational knowledge is expected.\n\n**Required**\n- Introductory programming experience in C or C++\n- Comfort with basic programming concepts such as functions, control flow, arrays, and structs\n\n**Helpful**\n- Introductory exposure to embedded systems\n- Introductory electronics knowledge\n\nIf you find that you are missing some of this background, reach out to us at **support@shortcct.com** and we can explore options to get you up to speed!"}]}');

-- 3.3 Industry Alignment
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-overview-industry', 'mod-overview', 'smartwatch-course', 'Industry Alignment', 'How the project aligns with industry skills', 'text', 2, 1,
'{"sections":[{"title":"Industry Alignment","content":"We analyzed the most in-demand skills across 50+ companies hiring embedded systems engineering interns. Below is how the Smartwatch Project aligns with those skills.\n\n**Core Skills** are fully covered in the base project.\n**Extendable Skills** can be developed through optional project extensions and the design challenge.\n**Not Covered** indicates skills that are outside the scope of the core project.","images":[{"url":"https://www.genspark.ai/api/files/s/2D27gI2m","alt":"Industry Alignment Skills Table","caption":"How the Smartwatch Project aligns with in-demand embedded systems skills"}]}]}');

-- 3.4 Documentation
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-overview-docs', 'mod-overview', 'smartwatch-course', 'Documentation', 'Required documentation and resources', 'text', 3, 1,
'{"sections":[{"title":"Documentation","content":"Here is the relevant documentation that you will need to use throughout the development of your project:\n\n**Datasheets**\n- [AXP202 Datasheet](https://linux-sunxi.org/images/2/20/AXP202_Datasheet_v1.0_en.pdf) - Power Management IC\n- [PCF8563 Datasheet](https://www.nxp.com/docs/en/data-sheet/PCF8563.pdf) - Real-Time Clock\n- [ST7789V Datasheet](https://www.displayfuture.com/Display/datasheet/controller/ST7789V.pdf) - Display Controller\n- [FT6236U Datasheet](https://www.buydisplay.com/download/ic/FT6236-FT6336-FT6436L-FT6436_Datasheet.pdf) - Touch Controller\n- [BMA423 Datasheet](https://www.mouser.com/datasheet/2/783/BSCH_S_A0010021471_1-2525113.pdf) - Accelerometer\n\n**Libraries**\n- [TFT_eSPI Library](https://doc-tft-espi.readthedocs.io/) - Display Graphics Library\n- [AXP202X_Library](https://github.com/lewisxhe/AXP202X_Library) - Power Management Library\n- [BMA423_Library](https://github.com/lewisxhe/BMA423_Library/tree/master) - Accelerometer Library\n\n**Other**\n- [T-Watch Pinout](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/master/docs/watch_2020_v3.md)\n- [T-Watch Schematic](https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/master/Schematic/T_WATCH-2020V03.pdf)"}]}');

-- 3.5 Set Up Smartwatch
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-overview-setup', 'mod-overview', 'smartwatch-course', 'Set Up Smartwatch', 'Environment setup instructions', 'text', 4, 1,
'{"video_url":"https://www.youtube.com/watch?v=52L8VP05elU","sections":[{"title":"Set Up Smartwatch","content":"To set up PlatformIO, this video by DroneBot Workshop is a great resource. It includes installation steps for Linux, MacOS, and Windows. You can download the latest versions of Python and Visual Studio Code.\n\nOnce you have downloaded PlatformIO on your system, watch the following video to set up your environment for our project.\n\nThe following video shows you how to clone our GitHub repository, [short-circuit-projects/smartwatch](https://github.com/short-circuit-projects/smartwatch), to VSCode. This tutorial is done on Windows, so it will look different on Linux or MacOS."}]}');

-- ============================================================================
-- STEP 4: MODULE 2 - TRAINING MATERIAL (12 sub-modules)
-- ============================================================================

-- 4.1 Complete Project Overview
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-training-overview', 'mod-training', 'smartwatch-course', 'Complete Project Overview', 'Video overview of the complete project', 'video', 0, 1,
'{"video_url":"https://www.youtube.com/watch?v=52L8VP05elU","sections":[{"title":"Complete Project Overview","content":"Watch this video for a complete overview of the smartwatch project."}]}');

-- 4.2 Modular Architecture
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-training-modular', 'mod-training', 'smartwatch-course', 'Modular Architecture', 'Understanding modular firmware architecture', 'text', 1, 1,
'{"sections":[
{"title":"Modular Architecture","content":"In professional embedded systems, firmware is rarely written as a single file. Instead, it is structured to be modular, maintainable, and scalable so that systems can grow, be debugged efficiently, and be worked on by multiple engineers.\n\nWe organize code into clear layers and clean file boundaries. This makes each component independent and easier to debug, extend, or replace. In PlatformIO it is recommended that you use the /include and /src for your header (.h) and source (.c/.cpp) files respectively."},
{"title":"File Structure","content":"In C and C++ projects, header files define the interface, while source files implement the functionality. This separation allows different parts of the program to interact through well-defined boundaries.\n\nHeader files contain declarations, not executable code. Their purpose is to describe what a module provides, not how it works. Other files include a header file to understand how to use the functions, data types, or classes defined by that module.\n\nA typical header file includes function prototypes for functions implemented elsewhere, constant definitions, and data type declarations such as struct, enum, or typedef. In C++ projects, header files may also contain class declarations that define the public interface of a class without exposing its internal implementation details."},
{"title":"Header File (accel.h)","content":"Header files declare the public interface. They tell other files what functions and types are available without revealing implementation details.","images":[{"url":"https://www.genspark.ai/api/files/s/W6YXjNvj","alt":"Header file example showing accel.h","caption":"Header File (accel.h)"}]},
{"title":"C Source File (accel.c)","content":"C source files contain the actual implementations of the functions and logic declared in their corresponding header files. This is where executable code lives and where the behavior of a module is defined.\n\nThese files typically include function definitions, internal helper functions, and low-level hardware or driver logic. Helper functions are often marked as static to limit their visibility to the file itself, helping enforce clean module boundaries and prevent unintended use elsewhere in the codebase.","images":[{"url":"https://www.genspark.ai/api/files/s/cjAQlIAb","alt":"Source file example showing accel.c","caption":"C Source File (accel.c)"}]},
{"title":"C++ Source File (display.cpp)","content":"C++ source files serve the same purpose as .c files but are used when the project relies on C++ features such as classes, objects, and encapsulation. They contain implementations of class methods and support object-oriented design patterns that improve code organization and reuse.\n\nIn embedded systems, .cpp files are commonly used when interacting with C++ based libraries such as Arduino or FreeRTOS, or when structuring more complex application logic. While the underlying principles remain the same, C++ enables more expressive abstractions on top of low-level embedded functionality.","images":[{"url":"https://www.genspark.ai/api/files/s/KrdlcPTc","alt":"C++ source file example showing display.cpp","caption":"C++ Source File (display.cpp)"}]},
{"title":"Project Layers","content":"Well-structured embedded firmware is typically organized into logical layers, where each layer has a clearly defined responsibility. This layered approach improves modularity, simplifies debugging, and allows systems to scale without becoming difficult to maintain. A clean project may include up to five conceptual layers. Not every project will implement all five explicitly, but understanding the role of each layer is fundamental to writing professional embedded firmware.\n\n**Layer 1: Hardware**\nThis layer consists of the physical electronics themselves, including microcontrollers, sensors, displays, and power components. No software exists at this level. All higher layers ultimately interact with the hardware, either directly or indirectly.\n\n**Layer 2: Hardware Abstraction Layer (HAL)**\nThe Hardware Abstraction Layer is the lowest level of software that interacts directly with the hardware. Its purpose is to provide readable and reusable APIs that abstract away hardware registers and low-level details. By isolating register access and device-specific behavior within the HAL, the rest of the system can interact with hardware in a safer and more portable way.\n\n**Layer 3: Operating System / Middleware / Service Layer**\nThis layer sits above the hardware drivers and provides reusable software services. It combines low-level drivers into higher-level capabilities such as task scheduling, timing services, communication stacks, or sensor management. In systems that use an RTOS, this layer often includes OS services and middleware components that support concurrency and inter-task communication.\n\n**Layer 4: Application Logic Layer**\nThe application logic layer defines the behavior of the device. It manages system states, decision-making, and interactions between components. This layer acts as the \"brain\" of the system, implementing the product''s functionality without being tied to specific hardware details.\n\n**Layer 5: Application Interface Layer**\nThe application interface layer is the topmost layer and is responsible for presenting information to the user or exposing APIs to other systems. This may include user interfaces, display logic, input handling, or external communication interfaces."}
]}');

-- 4.3 Pointers and References
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-training-pointers', 'mod-training', 'smartwatch-course', 'Pointers and References', 'Understanding pointers and references in embedded C/C++', 'text', 2, 1,
'{"video_url":"https://www.youtube.com/watch?v=syy-3fVicUc","sections":[
{"title":"Pointers and References","content":"Pointers and references are foundational concepts in embedded firmware development. They enable efficient data handling, direct hardware interaction, and flexible system design: especially in resource-constrained environments.\n\nA pointer is a variable that stores the memory address of another variable. A reference (C++ only) is an alias for an existing variable. References provide a safer and more readable syntax by eliminating the need for explicit dereferencing in most cases.\n\nIn embedded systems, pointers and references are commonly used to pass large data structures without copying, allow functions to modify variables directly, interface with hardware registers and memory-mapped I/O, and manage buffers, arrays, and shared state between tasks."},
{"title":"Pointer Basics","content":"A pointer is declared by specifying the type of data it points to, followed by an asterisk.\n\n```c\nint *ptr;\n```\n\nThis declares ptr as a pointer capable of holding the address of an integer.\n\nTo assign a pointer, use the address-of operator (&) to store the address of an existing variable:\n\n```c\nptr = &x;\n```\n\nTo access or modify the value at the address stored in the pointer, use the dereference operator (*):\n\n```c\n*ptr = 10;\n```\n\nThis modifies the value of the variable that ptr points to, not the pointer itself."},
{"title":"Passing by Pointer vs Value","content":"When a variable is passed by value to a function, the function receives a copy of that variable. Any modifications made inside the function affect only the copy and are not reflected outside the function.\n\nWhen a variable is passed by pointer, the function receives the address of the original variable. Modifying the value through the pointer directly affects the original data. This behavior is essential in embedded systems, where functions often need to update sensor readings, system state, or configuration values.","images":[{"url":"https://www.genspark.ai/api/files/s/OyaALdF5","alt":"Pass by value vs pointer comparison","caption":"Pass by Value vs Pass by Pointer"}]},
{"title":"Pointers and Arrays","content":"In C and C++, arrays automatically decay into pointers when passed to functions. This means the function receives a pointer to the first element of the array rather than a copy of the entire array.\n\nThis behavior is especially useful when working with buffers, such as reading and writing I2C data, handling communication packets, or processing sensor data streams. Changes made to the array within the function are reflected in the original array.","images":[{"url":"https://www.genspark.ai/api/files/s/p8A1J3Lm","alt":"Array passed as pointer","caption":"Arrays Decay to Pointers"}]},
{"title":"Pointers to Structures","content":"Embedded drivers commonly pass structures by pointer so that functions can populate or modify multiple related values at once. This syntax simplifies access to structure fields when working with pointers and is widely used in embedded driver code.","images":[{"url":"https://www.genspark.ai/api/files/s/gLkYh9Wv","alt":"Pointer to structure example","caption":"Passing Structures by Pointer"}]},
{"title":"References (C++ Only)","content":"References provide a cleaner alternative to pointers in C++. A reference acts as an alias for an existing variable, allowing functions to access and modify data without using explicit pointer syntax.\n\nBecause references cannot be null and cannot be reseated after initialization, they are often safer and easier to reason about than raw pointers in application-level C++ code.","images":[{"url":"https://www.genspark.ai/api/files/s/Q7mNpRsT","alt":"C++ reference example","caption":"C++ References"}]},
{"title":"Const Pointers and Pointer-to-Const","content":"The const keyword can be applied to pointers in different ways, each with a specific meaning.\n\nA constant pointer (int *const p) means the pointer cannot point to a different address, but the value it points to can change.\n\nA pointer to constant data (const int *p) means the pointer can change, but the value it points to cannot be modified.\n\nA constant pointer to constant data (const int *const p) means neither the pointer nor the value can change.\n\nCorrect use of const improves code safety and makes intent explicit.","images":[{"url":"https://www.genspark.ai/api/files/s/jH4kLmNp","alt":"Const pointer in function signature","caption":"Const Pointers for Safety"}]},
{"title":"Pointers in Interrupts and Tasks","content":"When variables are shared between an interrupt service routine (ISR) and other code, they must be declared as volatile to prevent the compiler from making incorrect optimization assumptions.\n\nTasks or main-loop code often access shared flags or state through pointers or references. Care must be taken to ensure data consistency and avoid race conditions when working across execution contexts.\n\nWhen you pass a variable by value in a function, you are passing a copy of the variable to a function. Therefore if you modify the variable within the function, the variable outside of the function will not be changed. On the other hand, if you pass the variable by pointer, then if you modify the variable within the function, that will be reflected outside of the function as well.","images":[{"url":"https://www.genspark.ai/api/files/s/rS5tUvWx","alt":"Volatile variable for ISR","caption":"Volatile Variables in Interrupts"}]},
{"title":"Common Issues","content":"Pointer-related bugs are a frequent source of crashes and unpredictable behavior in embedded systems. Common issues include using uninitialized pointers, forgetting to dereference a pointer, dereferencing a null pointer, returning or storing pointers to stack variables, and confusing the address-of (&) and dereference (*) operators.\n\nUnderstanding these failure modes is essential for writing safe and reliable firmware.\n\nPointers can be a challenging topic when first encountered. The following video by Nicolai Nielsen provides a clear and practical overview and is recommended if you would like additional reinforcement."}
]}');

-- 4.4 Bit Manipulation
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-training-bits', 'mod-training', 'smartwatch-course', 'Bit Manipulation', 'Working with bits and bitwise operations', 'text', 3, 1,
'{"video_url":"https://www.youtube.com/watch?v=WBim3afbYQw","sections":[
{"title":"Bit Manipulation","content":"Embedded hardware frequently represents information using individual bits, bit fields, and packed binary values. Configuration registers, status flags, and sensor data are often encoded in ways that require firmware to extract or modify only specific portions of a byte or word.\n\nFor example, the PCF8563 real-time clock stores the hour value in a six-bit field rather than a full byte, while many I2C sensors reserve a single bit (often bit 7) to signal conditions such as new data availability or error states. Because of this, embedded developers must be comfortable reading individual bits, clearing or setting specific flags, updating bit fields, and combining multiple binary fields into meaningful values.\n\nBitwise operators can be applied to values written in binary, hexadecimal, or decimal form. When referring to bit positions within a byte, bits are indexed from right to left, starting at bit 0. For an 8-bit value, this corresponds to positions 7 6 5 4 3 2 1 0.\n\nThe following video from Portfolio Courses offers a great introduction into binary numbers, and bitwise operators. We highly recommend watching this if you are unfamiliar with binary numbers."},
{"title":"Common Bitwise Operators","content":"Bitwise operators operate directly on the binary representation of values and are fundamental tools in embedded C and C++ programming.\n\nThe AND (&) operator is commonly used to select or clear specific bits by masking out unwanted portions of a value. The OR (|) operator is used to set specific bits without affecting others, while the XOR (^) operator toggles bits based on their current state.\n\nShift operators are also widely used. A left shift (<<) moves bits to the left and is often equivalent to multiplying by a power of two, while a right shift (>>) moves bits to the right and is often equivalent to dividing by a power of two. The bitwise NOT (~) operator inverts all bits in a value, turning ones into zeros and zeros into ones.\n\nThese operators are essential when working with hardware registers, configuration fields, and communication protocols.\n\n| Operator | Meaning | Example | Result |\n|----------|---------|---------|--------|\n| & | AND (clear or select specific bits) | 0b10110111 & 0b01111111 | 0b00110111 |\n| \\| | OR (used to set specific bits) | 0b10101110 \\| 0b01010001 | 0b11111111 |\n| ^ | XOR (used to flip a bit) | 0b00000101 ^ 0b00000001 | 0b00000100 |\n| << | Left shift | 1 << 3 | 0b00001000 |\n| >> | Right shift | 0b10000000 >> 4 | 0b00001000 |\n| ~ | Bitwise NOT (inverts all bits) | ~0x0F | 0xF0 |"},
{"title":"Bit Masking","content":"A bit mask is a predefined binary pattern used to isolate or manipulate specific bits within a larger value. Masks are commonly applied using the AND operator to clear unwanted bits or using the OR operator to set desired bits.\n\nFor example, the hexadecimal value 0x7F corresponds to the binary pattern 0111 1111. Applying this mask clears bit 7 while preserving the lower seven bits. This technique is frequently used when a register contains both data and status flags within the same byte.\n\nIn the case of the PCF8563 RTC, the seconds register stores valid time data in bits 0 through 6, while bit 7 indicates clock integrity. When reading this register, firmware must apply a mask to remove the flag bit before converting the remaining value. The resulting masked value can then be converted from binary-coded decimal (BCD) to a standard decimal format before being stored in the system''s time structure.","images":[{"url":"https://www.genspark.ai/api/files/s/yZ6aBcDe","alt":"BCD masking example","caption":"PCF8563 Seconds Extraction Example"}]},
{"title":"Other Bit Operations","content":"In addition to masking, firmware often needs to modify individual bits without disturbing the rest of a register.\n\nSetting a bit is typically done using a bitwise OR operation, which forces a specific bit to one while leaving all others unchanged.\n\nClearing a bit is accomplished by ANDing the value with the inverse of a bit mask, forcing the selected bit to zero.\n\nToggling a bit uses the XOR operator to flip the bit''s current state.\n\nMore complex operations involve updating a bit field, where multiple adjacent bits represent a single value. In these cases, the existing bits are first cleared using a mask, and the new value is then shifted into position and ORed into the cleared space. This pattern is commonly used when writing configuration values to control registers.\n\nFinally, embedded systems often need to combine or split bytes and nibbles. Upper and lower nibbles can be extracted using masks and shifts, or combined by shifting one value into position and ORing it with another. These techniques are especially common when parsing multi-byte sensor data or constructing command packets for communication protocols.","images":[
{"url":"https://www.genspark.ai/api/files/s/fG7hIjKl","alt":"Setting bit 3 example","caption":"Setting Bits Example (Sets Bit 3 in Reg to 1)"},
{"url":"https://www.genspark.ai/api/files/s/mN8oPqRs","alt":"Clearing bit 2 example","caption":"Clearing Bits Example (Forces Bit 2 in Reg to be 0)"},
{"url":"https://www.genspark.ai/api/files/s/tU9vWxYz","alt":"Toggling a bit example","caption":"Toggling Bits Example (Flips Bit 1 in Reg to 0 or 1)"},
{"url":"https://www.genspark.ai/api/files/s/aB1cDeFg","alt":"Bit field manipulation","caption":"Writing a Bit Field (Clear the Only Bit You Want to Update then OR the New Value into the Cleared Space)"},
{"url":"https://www.genspark.ai/api/files/s/hI2jKlMn","alt":"Combining nibbles","caption":"Combining Two Nibbles (Upper/Lower Bytes)"}
]}
]}');

-- 4.5 I2C Communication
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-training-i2c', 'mod-training', 'smartwatch-course', 'I2C Communication', 'Understanding I2C protocol and implementation', 'text', 4, 1,
'{"video_url":"https://www.youtube.com/watch?v=CAvawEcxoPU","sections":[
{"title":"I2C Communication","content":"I2C (Inter-Integrated Circuit) is a widely used two-wire serial communication protocol for connecting microcontrollers to peripheral devices such as sensors, displays, real-time clocks, and power-management ICs. It is especially popular in embedded systems because it allows multiple devices to share the same communication bus with minimal wiring.\n\nThe bus consists of two signals: SCL, the serial clock line driven by the master to synchronize communication, and SDA, a bidirectional data line used to transmit and receive information. A single master device, such as the ESP32, controls communication with one or more slave devices, each of which is identified by a unique 7-bit address (for example, 0x51 or 0x19). All devices on the bus share the same SDA and SCL lines.\n\nElectrically, I2C uses an open-drain configuration. Devices are only allowed to pull the lines low and never drive them high. For this reason, external pull-up resistors are required to bring the lines high when they are idle. These pull-ups are typically around 4.7k ohms. On the T-Watch platform, the required pull-up resistors are already present on the board.\n\nEvery I2C transaction follows a defined sequence: a START condition, transmission of the slave address with a read/write bit, an acknowledgment (ACK) from the receiver, one or more data bytes with acknowledgments after each byte, and finally a STOP condition. Understanding this sequence is essential for debugging and low-level driver development."},
{"title":"Reading the Datasheet and Schematics","content":"Before writing any I2C driver code, it is critical to study both the schematic and the device datasheet. The schematic tells you how the hardware is wired, while the datasheet defines how the device communicates.\n\nFrom the schematic, you must identify which pins are connected to SDA and SCL, as well as which I2C bus instance is being used (for example, I2C_NUM_0 or I2C_NUM_1). From the datasheet, you must determine the device''s 7-bit I2C address, understand the register map that defines how data is stored, and verify the maximum supported clock speed. The I2C master must operate at a frequency that is equal to or lower than what the peripheral supports. Failing to extract this information correctly is one of the most common causes of I2C communication errors."},
{"title":"Driver Architecture","content":"Well-structured I2C drivers are typically written in layers. The lowest layer is the bus layer, which handles raw I2C transactions such as initializing the bus, sending bytes, and reading bytes. This layer is responsible for interacting directly with the hardware driver provided by the platform.\n\nAbove the bus layer sits the driver logic, which interprets device-specific register layouts and data formats. At the top is the API layer, which exposes simple, readable functions that the rest of the application can use without needing to understand low-level I2C details. The number of layers in between depends on the complexity of the peripheral and the overall system, but separating concerns in this way improves maintainability and reuse."},
{"title":"Error Handling","content":"When writing low-level I2C drivers, it is essential to continuously verify that each communication step completes successfully. On the ESP32 platform, I2C functions typically return an esp_err_t value. Every call should store this return value and check whether it equals ESP_OK. Any other value indicates that an error occurred during communication and should be handled or reported appropriately. Robust error handling at the driver level makes higher-level debugging significantly easier."},
{"title":"Example","content":"Consider an environmental sensor that measures temperature in Celsius and exposes its data through I2C registers. The sensor uses SDA on pin 13, SCL on pin 14, operates on I2C_NUM_0, supports a clock frequency of 100 kHz, and has a 7-bit I2C address of 0x24. The device stores five consecutive temperature samples in registers 0x08 through 0x12, with each register using the same data format.\n\nEach temperature register encodes its value using a binary-coded decimal (BCD) format. The most significant bit (bit 7) is used as a sign bit, where a value of 0 indicates a positive temperature and a value of 1 indicates a negative temperature. Bits 6 through 4 store the tens digit of the temperature value, while bits 3 through 0 store the units digit. The sign bit does not contribute to the magnitude and must be handled separately in firmware.\n\nTo make the driver easier to read and maintain, key configuration values should be defined at the top of the header file using #define statements. This avoids hard-coding values throughout the codebase and simplifies future changes.","images":[{"url":"https://www.genspark.ai/api/files/s/vW4xYzAb","alt":"I2C configuration defines","caption":"I2C Pin and Address Configuration"}]},
{"title":"I2C Initialization","content":"At the C source level, the driver begins by initializing the I2C bus using the desired configuration parameters. The initialization function typically returns an error code indicating whether the bus was configured successfully. The configuration structure used during initialization defines parameters such as pin assignments, clock speed, and I2C mode.","images":[{"url":"https://www.genspark.ai/api/files/s/cD5eFgHi","alt":"I2C initialization code","caption":"I2C Master Initialization"}]},
{"title":"Read and Write Functions","content":"Once the bus is initialized, the driver can implement low-level read and write functions that operate on individual bytes or registers. These functions form the foundation of the driver and are responsible for all direct communication with the peripheral.\n\nOn top of these low-level functions, higher-level driver functions can be written to read temperature registers, apply bit masks to extract the sign and BCD digits, convert the BCD values to decimal, and return usable temperature values to the application layer.","images":[{"url":"https://www.genspark.ai/api/files/s/jK6lMnOp","alt":"I2C read write functions","caption":"I2C Driver Read/Write Functions"}]},
{"title":"Wire Library","content":"For this project, direct use of the Arduino Wire library is not required for all peripherals. Devices such as the AXP202 power-management IC and the BMA423 accelerometer provide helper objects that internally manage I2C communication.\n\nWhen the Wire library is required, it must be initialized explicitly with the correct pin assignments:\n\n```cpp\nWire.begin(I2C_MASTER_SDA, I2C_MASTER_SCL);\n```\n\nAdditional information about the Wire library can be found in the official Arduino documentation."},
{"title":"Common Debugging Tips","content":"When I2C communication does not behave as expected, the first step is to verify the slave address. Many devices have multiple possible addresses depending on pin configuration or revision, so always confirm that the address used in firmware matches the value specified in the datasheet (for example, 0x19, 0x68, or 0x51).\n\nNext, check the electrical integrity of the bus. Both SDA and SCL must have proper pull-up resistors, as I2C lines are open-drain and can only be driven low by devices. When the bus is idle, both lines should remain high. In this project, the required pull-up resistors are already present on the board, but this assumption should always be verified against the schematic.\n\nA simple and effective debugging technique is to write a minimal test routine that probes for device acknowledgments on the bus. Scanning for known I2C addresses or attempting a single register read can quickly confirm whether a peripheral is physically present and responding.\n\nIn systems that use multiple tasks or threads, I2C access must be serialized. Protect all I2C transactions with a mutex or other synchronization mechanism to prevent overlapping transactions, which can corrupt communication and lead to unpredictable behavior.\n\nFinally, remember that many I2C issues stem from incorrect assumptions about wiring, timing, or register layouts rather than from the protocol itself. Methodical verification of each layer, hardware, configuration, and driver logic, will resolve the majority of communication problems.\n\nThis video from Rohde & Schwarz offers a great overview of the I2C protocol. We highly recommend watching it if you are interested in learning the low level details of the protocol."}
]}');

-- 4.6 Object-Oriented Basics
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-training-oop', 'mod-training', 'smartwatch-course', 'Object-Oriented Basics', 'OOP concepts for embedded systems', 'text', 5, 1,
'{"sections":[
{"title":"Object-Oriented Basics","content":"In embedded firmware projects, object oriented programming helps manage complexity as systems grow. When used appropriately, it allows code to be organized into clear, modular components such as display drivers, power management logic, or sensor interfaces, while keeping related data and functionality closely grouped.\n\nBy encapsulating hardware control logic within classes, object oriented programming reduces reliance on global variables, improves code readability, and minimizes unintended side effects. This approach makes firmware easier to debug, reuse, and scale as new features or peripherals are added."},
{"title":"Classes","content":"A class is a blueprint that defines both the data an object will hold and the functions that operate on that data. In embedded systems, a class often represents a single hardware component or logical subsystem.\n\nA class definition typically resides in a header file, where its interface is declared, while the implementation of its functions is placed in a corresponding cpp file. Defining classes in this way separates what a module does from how it does it, which is a key principle of clean firmware design.\n\nIt is important to note that a class itself does not consume memory. Memory is only allocated when an object of that class is created.","images":[{"url":"https://www.genspark.ai/api/files/s/qR7sTuVw","alt":"Motor class declaration","caption":"Basic Class Declaration"}]},
{"title":"Objects","content":"An object is an instance of a class that exists in memory. Each object represents a concrete realization of the class and maintains its own internal state.\n\nFor example, if a motor control class is instantiated twice, each object will have its own configuration and state, even though both objects share the same underlying class definition.","images":[{"url":"https://www.genspark.ai/api/files/s/xY8zAbCd","alt":"Creating class instances","caption":"Creating Multiple Objects"}]},
{"title":"Member Variables","content":"Member variables store the internal state of an object. In embedded firmware, these variables often represent configuration parameters, cached sensor values, or hardware state.\n\nEach object receives its own copy of all member variables, allowing multiple instances of the same class to operate independently without interfering with one another."},
{"title":"Member Functions","content":"Member functions define the behavior of an object and operate directly on its member variables.\n\nInternally, every member function receives an implicit pointer called this, which refers to the current object instance. This allows the function to access and modify the object''s internal state without explicitly passing pointers or references."},
{"title":"Public and Private Access","content":"Access specifiers control how other parts of the program interact with a class. Members declared as public are accessible from outside the class and define the official interface that other code can use. Members declared as private are only accessible within the class itself and are used to protect internal implementation details.\n\nFor example, calling a public function such as temp.getValue() is valid because it respects the class interface. Directly accessing a private variable like temp.rawValue is not allowed and results in a compile time error. This enforcement prevents accidental misuse of internal state and improves code safety.","images":[{"url":"https://www.genspark.ai/api/files/s/eF9gHiJk","alt":"Encapsulation with state variable","caption":"Encapsulation with Setter Method"}]},
{"title":"Full Example","content":"In a typical embedded project, the class interface is declared in a header file such as motor.h, while the implementation is provided in motor.cpp. The implementation file often begins with a constructor, which is responsible for initializing member variables, configuring pins, or setting up communication interfaces.\n\nThe application entry point, such as main.cpp, acts as the driver for the system. In this file, objects are instantiated and their public member functions are called to control behavior. This structure keeps application logic clean and readable while abstracting hardware details into well defined modules.","images":[
{"url":"https://www.genspark.ai/api/files/s/zA2bCdEf","alt":"Motor header file","caption":"motor.h"},
{"url":"https://www.genspark.ai/api/files/s/gH3iJkLm","alt":"Motor source file","caption":"motor.cpp"},
{"url":"https://www.genspark.ai/api/files/s/nO4pQrSt","alt":"Using motor class in main","caption":"main.cpp"}
]}
]}');

-- 4.7 Real Time Operating System
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-training-rtos', 'mod-training', 'smartwatch-course', 'Real Time Operating System', 'RTOS concepts and FreeRTOS implementation', 'text', 6, 1,
'{"video_url":"https://www.youtube.com/watch?v=F321087yYy4","sections":[
{"title":"Real Time Operating System","content":"A Real Time Operating System enables multiple pieces of code, known as tasks, to execute seemingly at the same time on a single processor. This is achieved through rapid context switching, where the operating system scheduler determines which task runs at any given moment based on priority and timing requirements.\n\nRTOS based designs are widely used in embedded systems that require predictable timing, concurrent behavior, and safe sharing of hardware resources."},
{"title":"Tasks","content":"A task represents an independent thread of execution managed by the RTOS scheduler. Each task has its own stack and execution context and runs concurrently with other tasks in the system.\n\nTasks are typically structured as infinite loops that repeatedly perform a specific function. Because tasks are managed by the scheduler, they must never return. Instead of using blocking delays, tasks should call vTaskDelay() to pause execution and allow other tasks to run. This enables cooperative multitasking and prevents unnecessary CPU blocking.\n\nWhen creating tasks, care must be taken to allocate sufficient stack space to support local variables and function calls. Creating too many tasks increases memory usage and introduces scheduling overhead, which can negatively impact system performance.","images":[{"url":"https://www.genspark.ai/api/files/s/uV5wXyZa","alt":"Basic task function","caption":"FreeRTOS Task Implementation Example"}]},
{"title":"Creating Tasks","content":"The RTOS scheduler selects which task runs next based on priority. Lower priority values indicate less critical tasks, while higher priority values are reserved for time critical operations. The highest priority level is typically used only for emergency handling or tasks triggered by interrupts.","images":[{"url":"https://www.genspark.ai/api/files/s/bC6dEfGh","alt":"xTaskCreate example","caption":"FreeRTOS Task Creation Example"}]},
{"title":"Semaphores","content":"Semaphores are synchronization mechanisms used to coordinate execution between tasks or between interrupts and tasks. They are essential for ensuring safe access to shared resources and for signaling when events occur.\n\nA binary semaphore acts as a simple lock or event flag. It is commonly used to signal a task when new data is available or when an interrupt has occurred. This mechanism allows interrupt service routines to remain short while deferring processing to a task."},
{"title":"Binary Semaphore","content":"A binary semaphore acts as a simple lock or event flag. It is commonly used to signal a task when new data is available or when an interrupt has occurred."},
{"title":"Mutex","content":"A mutex is a specialized form of semaphore designed to protect shared resources such as displays, serial ports, or communication buses. By ensuring that only one task accesses a resource at a time, mutexes prevent data corruption and ensure system stability.","images":[{"url":"https://www.genspark.ai/api/files/s/iJ7kLmNo","alt":"Task with mutex","caption":"Using Mutex in a Task"},{"url":"https://www.genspark.ai/api/files/s/pQ8rStUv","alt":"Mutex task display","caption":"Mutex Task Display Example"}]},
{"title":"Inter-Task Communication","content":"FreeRTOS provides several mechanisms for exchanging information between tasks.\n\n- **Queues** allow structured data or buffers to be sent from one task to another.\n- **Semaphores** provide synchronization and signaling between tasks or between interrupts and tasks.\n- **Task notifications** offer a lightweight one to one signaling mechanism with minimal overhead.\n- **Event groups** allow multiple flags to represent system wide states that can be shared across tasks.\n\nChoosing the appropriate communication mechanism depends on the type of data being exchanged and the timing requirements of the system.","images":[{"url":"https://www.genspark.ai/api/files/s/wX9yZaBc","alt":"Multiple tasks with mutex","caption":"Multiple Tasks Sharing a Resource"}]},
{"title":"Tips with RTOS","content":"FreeRTOS enables multitasking, deterministic timing, and safe resource sharing when used correctly.\n\n- Interrupt service routines should always be kept short, with semaphores or task notifications used to signal tasks that further processing is required.\n- Task priorities should be chosen carefully to prevent starvation of lower priority tasks.\n- Blocking calls such as delay() should be avoided in favor of vTaskDelay() to allow proper scheduling.\n- Any resource shared between multiple tasks must be protected using a mutex to maintain data integrity.\n\nThis video from DigiKey further explains Real Time Operating Systems. We highly recommend watching this video to get a deeper understanding of how it works and when it should be used."}
]}');

-- 4.8 Static and Volatile Keywords
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-training-static-volatile', 'mod-training', 'smartwatch-course', 'Static and Volatile Keywords', 'Understanding static and volatile in embedded C', 'text', 7, 1,
'{"sections":[
{"title":"Static and Volatile Keywords","content":"Embedded systems frequently operate under constraints such as limited memory, concurrent execution, and interaction with hardware through interrupts. In these environments, the static and volatile keywords play a critical role in ensuring that variables behave correctly and predictably. These keywords guide the compiler in how variables are stored, accessed, and optimized, which is essential for reliable embedded firmware."},
{"title":"The Static Keyword","content":"The static keyword controls the lifetime and visibility of variables and functions. Its behavior depends on where it is applied, but in all cases it alters how memory is allocated and how symbols are exposed to the rest of the program.\n\nWhen used on a local variable inside a function, static causes the variable to retain its value between function calls. Unlike a normal local variable, which is created on the stack and destroyed when the function returns, a static local variable is allocated once and persists for the lifetime of the program. This is useful for maintaining state across function invocations without relying on global variables.","images":[{"url":"https://www.genspark.ai/api/files/s/dE0fGhIj","alt":"Static variable example","caption":"Static Variable Persists Between Calls"}]},
{"title":"Static Functions","content":"When applied to a global variable, static limits the variable''s visibility to the source file in which it is declared. This prevents the variable from being accessed by other files and avoids unintended symbol collisions. File scoped static variables are commonly used in drivers to keep internal state private to the implementation.\n\nThe static keyword can also be applied to functions. A static function is only visible within the source file where it is defined. This is often used to hide helper functions that are not part of a module''s public interface, reinforcing encapsulation and improving code organization."},
{"title":"The Volatile Keyword","content":"The volatile keyword tells the compiler that a variable''s value may change at any time, even if the current code does not explicitly modify it. This is especially important in embedded systems where variables can be modified by interrupt service routines, hardware peripherals, or concurrent tasks.\n\nWithout volatile, the compiler may optimize code by caching a variable''s value in a register and reusing it, assuming that the value does not change unexpectedly. If a variable is modified by an interrupt, this optimization can cause the main program to miss updates, leading to incorrect or stuck behavior.\n\nDeclaring a variable as volatile forces the compiler to always read its value from memory, ensuring that changes made outside the current execution context are observed correctly.","images":[{"url":"https://www.genspark.ai/api/files/s/kL1mNoP1","alt":"Volatile with ISR","caption":"Volatile Variable for ISR Communication"}]},
{"title":"Using Static and Volatile Together","content":"In embedded systems, it is common to combine static and volatile on the same variable. In this case, static restricts the variable''s visibility to a single source file, while volatile ensures that the compiler does not optimize away accesses to it.\n\nThis combination is often used for variables that are shared between an interrupt service routine and the main program or a task. The result is a variable that is private to a driver, safe to access in real time, and correctly synchronized with hardware events.","images":[{"url":"https://www.genspark.ai/api/files/s/rS2tUvWx","alt":"Static volatile combined","caption":"Combining Static and Volatile"}]}
]}');

-- 4.9 Timing and Scheduling
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-training-timing', 'mod-training', 'smartwatch-course', 'Timing and Scheduling', 'Timing techniques for embedded systems', 'text', 8, 1,
'{"sections":[
{"title":"Timing and Scheduling","content":"Accurate timing is a fundamental aspect of embedded system design. In a smartwatch, nearly every subsystem depends on precise and predictable timing, including screen refreshes, accelerometer interrupts, power management, step counting, button and touch input, I2C communication, battery polling, and wireless synchronization. Poor timing decisions can lead to missed events, sluggish user interfaces, excessive power consumption, or complete system instability."},
{"title":"Blocking Delays","content":"A blocking delay halts program execution entirely for a specified period of time. During a blocking delay, the processor is unable to perform other work, which prevents background tasks, user interface updates, and time sensitive logic from running. This approach also wastes power because the CPU remains active while waiting.\n\nBlocking delays are occasionally useful during early hardware bring up, simple test routines, or linear demonstration code. However, they are inappropriate for production firmware in multitasking systems.\n\nIn smartwatch firmware, using blocking delays can freeze animations, disrupt step counting, interfere with wireless communication, and degrade overall system responsiveness. For this reason, blocking delays should be avoided outside of isolated testing scenarios.","images":[{"url":"https://www.genspark.ai/api/files/s/yZ3aBcDe","alt":"Blocking delay example","caption":"Blocking Delay - Simple but Inefficient"}]},
{"title":"Non-Blocking Delays","content":"Non blocking timing techniques allow code to execute at specific intervals without stopping the processor. Instead of pausing execution, the firmware checks elapsed time and performs actions only when the required interval has passed.\n\nThis approach enables synchronization with physical processes such as button presses, sensor updates, and display refresh cycles while allowing other parts of the system to continue running. Using non blocking delays improves responsiveness and reduces unnecessary power usage compared to blocking delays.\n\nDuring early stages of development, non blocking delays are often sufficient for tasks such as periodic display updates or simple polling loops. They provide a basic form of cooperative multitasking without requiring an operating system.","images":[{"url":"https://www.genspark.ai/api/files/s/fG4hIjKl","alt":"Non-blocking timing","caption":"Non-Blocking Timing with millis()"}]},
{"title":"FreeRTOS Timing","content":"When firmware is structured around a real time operating system, timing control should be handled within tasks using RTOS aware delay mechanisms. In FreeRTOS, this is accomplished using functions such as vTaskDelay().\n\nUnlike blocking delays or manual time checks, vTaskDelay() puts the calling task into a suspended state for a specified number of ticks. While the task is sleeping, the scheduler runs other tasks, allowing the system to remain responsive and power efficient. Timing accuracy is tied to the RTOS tick rate, which is typically one millisecond on the ESP32.\n\nOnce the RTOS is integrated, vTaskDelay() should be used for periodic tasks such as display updates, sensor polling, touch detection, and battery monitoring.","images":[{"url":"https://www.genspark.ai/api/files/s/mN5oPqRs","alt":"RTOS task delay","caption":"RTOS Task Delay with vTaskDelay()"}]},
{"title":"Hardware Timer Basics","content":"The ESP32 includes multiple hardware timers that operate independently of the CPU. These timers are driven by an internal clock source, support high resolution counting, and can generate interrupts with microsecond level precision.\n\nHardware timers are required for applications that demand extremely precise timing, such as high rate data sampling, pulse width modulation, motor control, or ultra low latency event handling. Because they bypass the RTOS scheduler, they are not affected by task switching delays.\n\nWhile students are not required to implement raw hardware timers in this project, understanding their role helps clarify how precise timing is achieved at the hardware level.","images":[{"url":"https://www.genspark.ai/api/files/s/tU6vWxYz","alt":"Hardware timer example","caption":"Hardware Timer Interrupt"}]},
{"title":"Peripheral Timing","content":"Many peripheral devices impose strict timing requirements that firmware must respect. Communication protocols such as I2C define timing constraints for start and stop conditions, clock stretching, and spacing between read and write operations. Violating these constraints can lead to bus lockups, missed input events, or unresponsive devices.\n\nTimekeeping peripherals such as real time clocks operate independently from the main processor. The PCF8563, for example, updates its internal counters at a fixed one hertz rate. Firmware should poll the RTC at a reasonable interval to update the user interface without wasting power by reading too frequently."},
{"title":"Debouncing","content":"Physical buttons and capacitive touch inputs are inherently noisy and can produce multiple transitions for a single user action. Debouncing is the process of filtering these transitions over time to detect a single, intentional input.\n\nEffective debouncing relies on accurate timing. Whether implemented in software or hardware, debounce logic uses time thresholds to distinguish between noise and valid input. Without proper debouncing, user input can appear inconsistent or unreliable.","images":[{"url":"https://www.genspark.ai/api/files/s/aB7cDeFg","alt":"Debounce timing","caption":"Debouncing Touch Input"}]}
]}');

-- 4.10 Interrupts and ISRs
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-training-interrupts', 'mod-training', 'smartwatch-course', 'Interrupts and ISRs', 'Understanding interrupts and interrupt service routines', 'text', 9, 1,
'{"sections":[
{"title":"Interrupts and ISRs","content":"Interrupts are a fundamental mechanism in embedded systems that allow the processor to respond immediately to external events or internal conditions without continuously polling for changes. When an interrupt occurs, the processor temporarily suspends its current execution, saves its state, and jumps to a special function called an Interrupt Service Routine (ISR).\n\nIn the smartwatch project, interrupts are used for handling button presses, touch events, accelerometer data ready signals, and timer-based events. Understanding how to properly implement and manage interrupts is essential for building responsive and efficient embedded systems."},
{"title":"ISR Best Practices","content":"Interrupt Service Routines must be kept as short as possible. The ISR should perform only the minimum work necessary to acknowledge the interrupt and signal the main program or a task that further processing is needed.\n\nCommon ISR tasks include:\n- Setting a flag variable (must be volatile)\n- Giving a semaphore or sending a task notification\n- Reading or clearing a hardware register\n\nTasks that should NOT be done in an ISR:\n- Serial printing or logging\n- Complex calculations\n- Memory allocation\n- Blocking calls or delays"},
{"title":"Volatile Variables in ISRs","content":"Any variable shared between an ISR and the main program must be declared as volatile. This tells the compiler that the variable can change at any time and prevents optimizations that could cause the main program to miss updates.\n\n```c\nvolatile bool buttonPressed = false;\n\nvoid IRAM_ATTR buttonISR() {\n    buttonPressed = true;\n}\n\nvoid loop() {\n    if (buttonPressed) {\n        buttonPressed = false;\n        handleButtonPress();\n    }\n}\n```"},
{"title":"IRAM_ATTR on ESP32","content":"On the ESP32, ISR functions should be marked with the IRAM_ATTR attribute. This places the function in internal RAM rather than flash memory, which is important because flash access can be interrupted during certain operations.\n\n```c\nvoid IRAM_ATTR myInterruptHandler() {\n    // Minimal ISR code here\n}\n```"}
]}');

-- 4.11 Finite State Machine
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-training-fsm', 'mod-training', 'smartwatch-course', 'Finite State Machine', 'Implementing state machines in embedded systems', 'text', 10, 1,
'{"sections":[
{"title":"Finite State Machine","content":"A finite state machine, or FSM, is a structured model used to organize system behavior into a finite number of well defined states, along with clear rules that govern transitions between those states. FSMs are widely used in embedded systems because they make behavior predictable, modular, and easy to reason about.\n\nAt any given time, the system exists in a single state that represents its current mode of operation. Transitions between states occur in response to events or conditions, such as a button press, a timer expiring, or new sensor data becoming available. Each state may execute specific actions when it is entered, while it is active, or when it is exited. This structure allows complex behavior to be expressed in a clear and maintainable way."},
{"title":"Example","content":"A common use of a finite state machine in smartwatch firmware is controlling the user interface. For example, the system may start in a home screen state. Each time the user presses a button or performs a gesture, the FSM transitions to the next screen state. The display update logic depends entirely on which state is currently active.\n\nBy separating screen behavior into distinct states, the firmware avoids large conditional blocks and makes it easy to add new screens or modify existing ones. Each screen state is responsible only for its own logic and display updates, while transitions define how the user moves between screens.","images":[{"url":"https://www.genspark.ai/api/files/s/hI8jKlMn","alt":"FSM implementation with switch statement","caption":"FSM Implementation for Screen Navigation"}]},
{"title":"Implementation Guidance","content":"When implementing a finite state machine in embedded firmware, states should be represented using enumerated types to improve readability and reduce errors. The logic associated with each state should be kept isolated, either within dedicated functions or clearly defined sections of code. This makes the behavior of each state easier to understand and debug.\n\nState transitions can be implemented using switch statements or function pointers, depending on the complexity of the system. In firmware that uses a real time operating system, states may also be represented using task modes or shared flags, allowing the FSM to integrate cleanly with multitasking behavior.\n\nFinite state machines are especially effective for managing screens, button interactions, operating modes, and other event driven behavior in embedded systems. By enforcing clear structure and explicit transitions, FSMs help produce firmware that is reliable, predictable, and easy to extend."}
]}');

-- 4.12 Networking
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-training-networking', 'mod-training', 'smartwatch-course', 'Networking', 'WiFi and networking on ESP32', 'text', 11, 1,
'{"sections":[
{"title":"Networking","content":"Networking enables a micro controller to communicate with other devices over a shared medium. The ESP32 includes an integrated Wi Fi radio and a full TCP IP networking stack, allowing it to function much like a small computer on a local network. This capability enables features such as time synchronization, cloud communication, remote updates, and data logging.\n\nThe ESP32 can operate in two primary Wi Fi modes. In station mode, the device connects to an existing network such as a home router, mobile hotspot, or access point. In access point mode, the ESP32 creates its own wireless network that other devices can connect to directly. For most smartwatch applications, station mode is used so the device can connect to a known network and access internet based services."},
{"title":"Wi-Fi Connection Example","content":"Establishing a Wi Fi connection involves initializing the networking subsystem, providing network credentials, and waiting for a successful connection event. Once connected, the ESP32 is assigned an IP address by the network, which allows it to communicate with other devices and services using standard internet protocols.\n\nIn a smartwatch context, Wi Fi connectivity should be handled carefully to balance functionality and power consumption. Connections are typically established only when needed, such as during initial setup, time synchronization, or data transfer, and disabled afterward to conserve battery life.","images":[{"url":"https://www.genspark.ai/api/files/s/52YAFb3q","alt":"WiFi connection code","caption":"Basic WiFi Connection"}]},
{"title":"Wi-Fi Time Synchronization Example","content":"One common use of Wi Fi in smartwatch firmware is synchronizing the real time clock with an external time source. This is typically done using the Network Time Protocol, which allows the device to retrieve the current time from an internet time server.\n\nAfter a successful Wi Fi connection is established, the firmware can request the current time using NTP and update the real time clock accordingly. This ensures that the watch maintains accurate time even after power cycles or extended periods without user interaction. Using a consistent sequence of initialization, connection, and synchronization steps improves reliability and simplifies debugging.","images":[{"url":"https://www.genspark.ai/api/files/s/S6mWhW98","alt":"NTP time sync example","caption":"NTP Time Synchronization"}]}
]}');

-- ============================================================================
-- STEP 5: MODULE 3 - PROJECT MODULES (7 sub-modules)
-- ============================================================================

-- 5.1 Module 1
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-project-mod1', 'mod-projects', 'smartwatch-course', 'Module 1', 'System Boot - Power, Display, and Interrupts', 'text', 0, 1,
'{"sections":[
{"title":"Module 1","content":"In this module, you will bring the smartwatch to life by initializing system power, displaying output on the screen, and handling a hardware interrupt. By the end of this module, the watch should successfully boot, display text, and respond to a button press."},
{"title":"Task 1: Initialize System Power Using the AXP202","content":"Configure the power management system so the watch can boot and supply power to required peripherals.\n\n**Implementation Guidance**\n- Use the AXP20X.h library to control the AXP202 power management IC\n- Establish I2C communication with the AXP202\n- Identify required power rails using the schematic\n- Enable the appropriate LDOs to power the system and display\n- Review example code provided by the AXP20X library"},
{"title":"Task 2: Display Text Using TFT_eSPI","content":"Verify that the display is functioning by printing text after system boot.\n\n**Implementation Guidance**\n- Use the TFT_eSPI library to interface with the display\n- Initialize the display before writing any graphics\n- Print the text \"Hello World\" after boot\n- Experiment with text color, background color, and position"},
{"title":"Task 3: Implement a Hardware Interrupt for the Power Button","content":"Use a hardware interrupt to toggle the display on and off using the side button.\n\n**Implementation Guidance**\n- The side button is connected to the interrupt pin of the AXP202\n- Identify the correct interrupt pin using the schematic\n- Refer to the Interrupts and ISRs section for proper ISR structure\n- Keep the ISR minimal and defer logic to the main program or task\n- Use a shared flag or notification to toggle display state"},
{"title":"Deliverables and File Structure","content":"All code for this module must be implemented using the following structure:\n\n- **power.h** and **power.cpp** handles AXP202 power initialization and control\n- **display.h** and **display.cpp** handles display initialization and graphics output\n- **main.cpp** coordinates system startup and high-level behavior\n\nNo functionality should be implemented directly inside main.cpp beyond initialization and high-level control."}
]}');

-- 5.2 Module 2
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-project-mod2', 'mod-projects', 'smartwatch-course', 'Module 2', 'Timekeeping - RTC, WiFi Sync, and Display', 'text', 1, 1,
'{"sections":[
{"title":"Module 2","content":"In this module, you will implement full system timekeeping for the smartwatch. You will store and retrieve time using a real time clock, synchronize time over Wi-Fi when available, and display the current date and time on the screen at controlled intervals. By the end of this module, the watch should maintain accurate time across reboots and update its display efficiently."},
{"title":"Task 1: Implement Real Time Clock Storage and Retrieval","content":"Use the PCF8563 real time clock to store and retrieve the current date and time.\n\nYou must design functions in mytime.h and mytime.c that allow the system to write time data to the RTC and read it back. These functions should then be used from main.cpp. Time should be stored in twenty four hour format, where hours and minutes range from 00:00 to 23:59. The date should include the month, day, and year.\n\nAll firmware for this task must be written in C and use only the libraries provided in the repository. In particular, you should rely on driver/i2c.h and esp_err.h for low level communication and error handling.\n\n**Implementation Guidance**\n- Use the tm structure from the standard time library to represent date and time values\n- Consider writing low level byte read and write functions for the RTC, then wrapping them with higher level functions used outside of mytime.c\n- Use the provided bcdToDec and decToBcd helper functions when reading from or writing to RTC registers\n- Carefully study the PCF8563 datasheet to understand register layout, bit masking, and valid value ranges"},
{"title":"Task 2: Synchronization Time Using Wi-Fi","content":"Attempt to connect to a Wi Fi network during system boot and retrieve the current time if a connection is successfully established.\n\nUse the WiFi.h library to initialize the Wi Fi subsystem and connect to a known network. Once connected, synchronize the system time using the Network Time Protocol.\n\n**Implementation Guidance**\n- Initialize Wi Fi and attempt a connection during startup\n- After connecting, call syncTimeWithNTP() followed by getLocalTime(&time) to retrieve the current time\n- If Wi Fi is unavailable, the system should continue operating using the RTC\n\n**Note:** The ESP32 supports only 2.4 GHz Wi Fi networks. If a 2.4 GHz network is not available, a personal hotspot can be used instead."},
{"title":"Task 3: Display Time and Date on the LCD","content":"Display the current time and date on the screen in a readable format.\n\nThe time must be shown in HH:MM format using military time. The date must be shown in MM DD YYYY format. The display should not update continuously. Instead, design your system so the screen refreshes only once every forty seconds.\n\n**Implementation Guidance**\n- Use snprintf to format time and date strings before sending them to the display\n- Ensure display updates are non blocking and do not interfere with other system tasks\n- Integrate this logic cleanly with your existing display driver"},
{"title":"Deliverables and File Structure","content":"All code for this module must be implemented using the following file structure:\n\n- **mytime.h** and **mytime.c** handles RTC communication and time conversion logic\n- **mywifi.h** and **mywifi.c** handles Wi Fi initialization and time synchronization\n- **display.h** and **display.cpp** handles rendering time and date on the screen\n- **power.h** and **power.cpp** maintains system power configuration\n- **main.cpp** coordinates initialization and high level system behavior\n\nTimekeeping logic should not be implemented directly in main.cpp. All functionality should be abstracted into appropriate modules."}
]}');

-- 5.3 Module 3
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-project-mod3', 'mod-projects', 'smartwatch-course', 'Module 3', 'Inputs and Sensors - Touch, Accelerometer, WiFi Status', 'text', 2, 1,
'{"sections":[
{"title":"Module 3","content":"In this module, you will expand the smartwatch user interface by integrating touch input, accelerometer data, and Wi-Fi status visualization. By the end of this module, the watch should respond to touch events, display step count information, and provide clear feedback about network connectivity through dedicated screens."},
{"title":"Task 1: Read and Display Touch Coordinates","content":"Create a program that prints the x and y coordinates of the user''s touch on the smartwatch display.\n\nYou will implement a low level C driver to communicate with the FT6236U touch controller and extract touch coordinates over I2C. Your driver functions should be written in a dedicated source and header file, and the touch handling logic should be integrated into main.cpp.\n\nTouch events must be detected using a hardware interrupt so that coordinates are updated only when the screen is actively touched.\n\n**Implementation Guidance**\n- The FT6236U uses an I2C address of 0x38, which is not explicitly listed in the datasheet\n- Use an interrupt driven approach to detect touch events\n- Keep interrupt handlers minimal and defer coordinate processing to normal application code\n- Ensure x and y coordinates are correctly parsed from the device registers"},
{"title":"Task 2: Design the Accelerometer Screen","content":"Create a screen that displays the total step count stored in the BMA423 accelerometer.\n\nThis screen must initialize the accelerometer, retrieve the stored step count, and display it in a readable format. All accelerometer related functionality should be implemented using the Accel class within accel.h and accel.cpp. The screen logic should then be driven from main.cpp.\n\n**Implementation Guidance**\n- Initialize the BMA423 before attempting to read step data\n- Use the provided accelerometer abstraction rather than accessing registers directly\n- Ensure the displayed step count reflects the value stored in the sensor"},
{"title":"Task 3: Design the Wi-Fi Status Screen","content":"Create a screen that displays the current Wi-Fi connection status of the smartwatch.\n\nThe screen must support three states:\n- Wi-Fi Connected\n- Wi-Fi Connecting\n- Wi-Fi Not Connected\n\nWhen Wi-Fi is connected, the network SSID should be displayed. When Wi-Fi is not connected, the screen should clearly indicate that no connection is present. When a connection attempt is in progress, the screen should reflect the connecting state.\n\nYou must also implement a button that allows the user to manually attempt to reconnect to the Wi-Fi network.\n\nAll Wi-Fi related functionality should be implemented in mywifi.h and mywifi.cpp using the MyWiFi class, with high level control handled in main.cpp.\n\n**Implementation Guidance**\n- Track Wi-Fi state internally and update the screen accordingly\n- Use the provided drawWiFiSymbol and drawRefreshSymbol helper functions to display icons\n- Ensure screen updates are responsive but not excessively frequent"},
{"title":"Deliverables and File Structure","content":"All code for this module must follow the structure below:\n\n- **touch.h** and **touch.c** handles FT6236U communication and coordinate extraction\n- **accel.h** and **accel.cpp** handles BMA423 initialization and step count retrieval\n- **mywifi.h** and **mywifi.cpp** handles Wi-Fi state management and reconnection logic\n- **display.h** and **display.cpp** handles rendering of all screens and symbols\n- **main.cpp** coordinates screen selection, input handling, and system behavior\n\nLow level drivers should not be implemented directly inside main.cpp. All functionality should be abstracted into appropriate modules."}
]}');

-- 5.4 Module 4
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-project-mod4', 'mod-projects', 'smartwatch-course', 'Module 4', 'Final Integration - Stopwatch, Navigation, Battery, RTOS', 'text', 3, 1,
'{"sections":[
{"title":"Module 4","content":"In this final module, you will integrate all previously developed components into a complete, responsive smartwatch application. You will design a stopwatch feature, implement full screen navigation, display live battery information, and structure the firmware using a real time operating system. By the end of this module, the smartwatch should behave like a cohesive product rather than a collection of individual features."},
{"title":"Task 1: Design a Stopwatch Screen","content":"Create a stopwatch screen that supports start, stop, and reset functionality.\n\nThe stopwatch must display time in HH MM SS format and continue running even when the stopwatch screen is not actively displayed. This requires separating stopwatch timing logic from display rendering logic.\n\n**Implementation Guidance**\n- Use semaphores to safely coordinate access to the display whenever screen content changes\n- Ensure the stopwatch state persists independently of the active screen\n- Avoid resetting or pausing the stopwatch when navigating between screens"},
{"title":"Task 2: Implement Screen Navigation Using Touch Buttons","content":"Design and implement touch buttons that allow the user to navigate between all previously created screens.\n\nYou must support navigation between the home screen, step count screen, Wi Fi screen, and stopwatch screen. Button interactions should be responsive and consistent across screens.\n\n**Implementation Guidance**\n- Centralize screen state management to avoid duplicated logic\n- Use touch events to trigger screen transitions rather than polling\n- Ensure only one screen is active at a time"},
{"title":"Task 3: Display Live Battery Percentage on the Home Screen","content":"Use the power management system to display the current battery percentage on the home screen.\n\nYou must read battery data using the AXP20X library and display the value using the provided drawBatterySymbol function. The battery percentage should update dynamically and reflect real system state.\n\n**Implementation Guidance**\n- Retrieve battery information through the AXP20X driver\n- Pass the battery percentage value into the display drawing function\n- Ensure battery updates do not interfere with other display operations"},
{"title":"Task 4: Design an RTOS Based System Architecture","content":"Structure the firmware using a real time operating system to handle multiple subsystems concurrently.\n\nYou should create tasks strategically to manage display updates, input handling, timekeeping, sensor polling, and networking. Tasks must be designed to operate reliably without blocking one another.\n\n**Implementation Guidance**\n- Assign appropriate priorities to tasks based on timing sensitivity\n- Use semaphores or task notifications for safe communication between tasks\n- Keep interrupt service routines minimal and defer processing to tasks"},
{"title":"Deliverables and File Structure","content":"All functionality in this module must integrate cleanly with the existing project structure:\n\n- Display related logic in **display.h** and **display.cpp**\n- Power and battery logic in **power.h** and **power.cpp**\n- Wi Fi logic in **mywifi.h** and **mywifi.cpp**\n- Sensor logic in existing accelerometer and touch files\n- Task coordination and system initialization in **main.cpp**\n\nNo new functionality should be implemented directly inside interrupts or without proper abstraction."}
]}');

-- 5.5 Short Circuit Design Challenge
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-project-challenge', 'mod-projects', 'smartwatch-course', 'Short Circuit Design Challenge', 'Design challenge information', 'text', 4, 1,
'{"sections":[
{"title":"Short Circuit Design Challenge","content":"The Short Circuit Design Challenge is an opportunity to extend your smartwatch project beyond the baseline requirements. This challenge encourages you to explore additional features, optimize your implementation, or add creative functionality that demonstrates your engineering skills.\n\n**Challenge Guidelines**\n- Build upon your completed baseline project\n- Implement one or more additional features of your choosing\n- Document your design decisions and implementation approach\n- Submit a demonstration video showing your extended functionality\n\n**Suggested Extensions**\n- Custom watch faces or themes\n- Additional sensor integration\n- Power optimization techniques\n- Notification systems\n- Data logging capabilities\n- Custom applications"}
]}');

-- 5.6 Baseline Project Upload
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-project-baseline', 'mod-projects', 'smartwatch-course', 'Baseline Project Upload', 'Submit your completed baseline project', 'submission', 5, 1,
'{"sections":[
{"title":"Baseline Project Upload","content":"Submit your completed baseline smartwatch project here. Your submission should include:\n\n**Required Files**\n- Complete source code (all .h, .c, .cpp files)\n- platformio.ini configuration file\n- Any custom libraries or dependencies\n\n**Submission Format**\n- Compress all project files into a single ZIP archive\n- Include a brief README describing your implementation\n- Ensure your code compiles without errors\n\n**Evaluation Criteria**\n- All four modules completed and functional\n- Clean code organization following the specified file structure\n- Proper use of hardware abstraction and modular design\n- Working demonstration of all required features"}
]}');

-- 5.7 Design Challenge Upload
INSERT INTO lessons (id, module_id, course_id, title, description, content_type, order_index, is_published, content_json)
VALUES ('lesson-project-designupload', 'mod-projects', 'smartwatch-course', 'Design Challenge Upload', 'Submit your design challenge project', 'submission', 6, 1,
'{"sections":[
{"title":"Design Challenge Upload","content":"Submit your design challenge project here. Your submission should demonstrate the additional features or improvements you have implemented beyond the baseline requirements.\n\n**Required Materials**\n- Complete source code with your extensions\n- Documentation of your design decisions\n- Video demonstration of your additional features\n\n**Submission Format**\n- Compress all project files into a single ZIP archive\n- Include a detailed README explaining your extensions\n- Provide a link to your demonstration video\n\n**Evaluation Criteria**\n- Creativity and innovation in your chosen extensions\n- Technical implementation quality\n- Integration with the baseline project\n- Clear documentation and presentation"}
]}');

-- ============================================================================
-- STEP 6: Update course total_lessons count
-- ============================================================================
UPDATE courses SET total_lessons = 24 WHERE id = 'smartwatch-course';
