-- Add step count image to Module 3 Task 2
UPDATE lessons 
SET content_json = '{
  "sections": [
    {"title": "Module 3", "content": "In this module, you will expand the smartwatch user interface by integrating touch input, accelerometer data, and Wi-Fi status visualization. By the end of this module, the watch should respond to touch events, display step count information, and provide clear feedback about network connectivity through dedicated screens.", "videos": [{"url": "/api/videos/touch-screen-function.mp4", "title": "Touch Screen Function Demo", "type": "r2"}]},
    {"title": "Task 1: Read and Display Touch Coordinates", "content": "Create a program that prints the x and y coordinates of the user touch on the smartwatch display.\n\nYou will implement a low level C driver to communicate with the FT6236U touch controller and extract touch coordinates over I2C. Your driver functions should be written in a dedicated source and header file, and the touch handling logic should be integrated into main.cpp.\n\nTouch events must be detected using a hardware interrupt so that coordinates are updated only when the screen is actively touched.\n\n**Implementation Guidance**\n- The FT6236U uses an I2C address of 0x38, which is not explicitly listed in the datasheet\n- Use an interrupt driven approach to detect touch events\n- Keep interrupt handlers minimal and defer coordinate processing to normal application code\n- Ensure x and y coordinates are correctly parsed from the device registers"},
    {"title": "Task 2: Design the Accelerometer Screen", "content": "Create a screen that displays the total step count stored in the BMA423 accelerometer.\n\nThis screen must initialize the accelerometer, retrieve the stored step count, and display it in a readable format. All accelerometer related functionality should be implemented using the Accel class within accel.h and accel.cpp. The screen logic should then be driven from main.cpp.\n\n**Implementation Guidance**\n- Initialize the BMA423 before attempting to read step data\n- Use the provided accelerometer abstraction rather than accessing registers directly\n- Ensure the displayed step count reflects the value stored in the sensor", "images": [{"url": "embedded:module3_step_count", "alt": "Smartwatch showing step count display", "caption": "Step Count Display on Smartwatch"}]},
    {"title": "Task 3: Design the Wi-Fi Status Screen", "content": "Create a screen that displays the current Wi-Fi connection status of the smartwatch.\n\nThe screen must support three states:\n- Wi-Fi Connected\n- Wi-Fi Connecting\n- Wi-Fi Not Connected\n\nWhen Wi-Fi is connected, the network SSID should be displayed. When Wi-Fi is not connected, the screen should clearly indicate that no connection is present. When a connection attempt is in progress, the screen should reflect the connecting state.\n\nYou must also implement a button that allows the user to manually attempt to reconnect to the Wi-Fi network.\n\nAll Wi-Fi related functionality should be implemented in mywifi.h and mywifi.cpp using the MyWiFi class, with high level control handled in main.cpp.\n\n**Implementation Guidance**\n- Track Wi-Fi state internally and update the screen accordingly\n- Use the provided drawWiFiSymbol and drawRefreshSymbol helper functions to display icons\n- Ensure screen updates are responsive but not excessively frequent", "videos": [{"url": "/api/videos/wifi-smartwatch.mp4", "title": "WiFi Smartwatch Demo", "type": "r2"}]},
    {"title": "Deliverables and File Structure", "content": "All code for this module must follow the structure below:\n\n- **touch.h** and **touch.c** handles FT6236U communication and coordinate extraction\n- **accel.h** and **accel.cpp** handles BMA423 initialization and step count retrieval\n- **mywifi.h** and **mywifi.cpp** handles Wi-Fi state management and reconnection logic\n- **display.h** and **display.cpp** handles rendering of all screens and symbols\n- **main.cpp** coordinates screen selection, input handling, and system behavior\n\nLow level drivers should not be implemented directly inside main.cpp. All functionality should be abstracted into appropriate modules."}
  ]
}'
WHERE id = 'lesson-project-mod3';
