-- Move step count image from Module 3 to Module 2 Task 2
-- First, update Module 2 to add the image after Task 2
UPDATE lessons 
SET content_json = '{"sections":[
{"title":"Module 2","content":"In this module, you will implement full system timekeeping for the smartwatch. You will store and retrieve time using a real time clock, synchronize time over Wi-Fi when available, and display the current date and time on the screen at controlled intervals. By the end of this module, the watch should maintain accurate time across reboots and update its display efficiently."},
{"title":"Task 1: Implement Real Time Clock Storage and Retrieval","content":"Use the PCF8563 real time clock to store and retrieve the current date and time.\n\nYou must design functions in mytime.h and mytime.c that allow the system to write time data to the RTC and read it back. These functions should then be used from main.cpp. Time should be stored in twenty four hour format, where hours and minutes range from 00:00 to 23:59. The date should include the month, day, and year.\n\nAll firmware for this task must be written in C and use only the libraries provided in the repository. In particular, you should rely on driver/i2c.h and esp_err.h for low level communication and error handling.\n\n**Implementation Guidance**\n- Use the tm structure from the standard time library to represent date and time values\n- Consider writing low level byte read and write functions for the RTC, then wrapping them with higher level functions used outside of mytime.c\n- Use the provided bcdToDec and decToBcd helper functions when reading from or writing to RTC registers\n- Carefully study the PCF8563 datasheet to understand register layout, bit masking, and valid value ranges"},
{"title":"Task 2: Synchronization Time Using Wi-Fi","content":"Attempt to connect to a Wi Fi network during system boot and retrieve the current time if a connection is successfully established.\n\nUse the WiFi.h library to initialize the Wi Fi subsystem and connect to a known network. Once connected, synchronize the system time using the Network Time Protocol.\n\n**Implementation Guidance**\n- Initialize Wi Fi and attempt a connection during startup\n- After connecting, call syncTimeWithNTP() followed by getLocalTime(&time) to retrieve the current time\n- If Wi Fi is unavailable, the system should continue operating using the RTC\n\n**Note:** The ESP32 supports only 2.4 GHz Wi Fi networks. If a 2.4 GHz network is not available, a personal hotspot can be used instead.", "images": [{"url": "embedded:module3_step_count", "alt": "Smartwatch displaying time and date", "caption": "Time and Date Display on Smartwatch"}]},
{"title":"Task 3: Display Time and Date on the LCD","content":"Display the current time and date on the screen in a readable format.\n\nThe time must be shown in HH:MM format using military time. The date must be shown in MM DD YYYY format. The display should not update continuously. Instead, design your system so the screen refreshes only once every forty seconds.\n\n**Implementation Guidance**\n- Use snprintf to format time and date strings before sending them to the display\n- Ensure display updates are non blocking and do not interfere with other system tasks\n- Integrate this logic cleanly with your existing display driver"},
{"title":"Deliverables and File Structure","content":"All code for this module must be implemented using the following file structure:\n\n- **mytime.h** and **mytime.c** handles RTC communication and time conversion logic\n- **mywifi.h** and **mywifi.c** handles Wi Fi initialization and time synchronization\n- **display.h** and **display.cpp** handles rendering time and date on the screen\n- **power.h** and **power.cpp** maintains system power configuration\n- **main.cpp** coordinates initialization and high level system behavior\n\nTimekeeping logic should not be implemented directly in main.cpp. All functionality should be abstracted into appropriate modules."}
]}'
WHERE id = 'lesson-project-mod2';

-- Remove image from Module 3 Task 2
UPDATE lessons 
SET content_json = '{
  "sections": [
    {"title": "Module 3", "content": "In this module, you will expand the smartwatch user interface by integrating touch input, accelerometer data, and Wi-Fi status visualization. By the end of this module, the watch should respond to touch events, display step count information, and provide clear feedback about network connectivity through dedicated screens.", "videos": [{"url": "/api/videos/touch-screen-function.mp4", "title": "Touch Screen Function Demo", "type": "r2"}]},
    {"title": "Task 1: Read and Display Touch Coordinates", "content": "Create a program that prints the x and y coordinates of the user touch on the smartwatch display.\n\nYou will implement a low level C driver to communicate with the FT6236U touch controller and extract touch coordinates over I2C. Your driver functions should be written in a dedicated source and header file, and the touch handling logic should be integrated into main.cpp.\n\nTouch events must be detected using a hardware interrupt so that coordinates are updated only when the screen is actively touched.\n\n**Implementation Guidance**\n- The FT6236U uses an I2C address of 0x38, which is not explicitly listed in the datasheet\n- Use an interrupt driven approach to detect touch events\n- Keep interrupt handlers minimal and defer coordinate processing to normal application code\n- Ensure x and y coordinates are correctly parsed from the device registers"},
    {"title": "Task 2: Design the Accelerometer Screen", "content": "Create a screen that displays the total step count stored in the BMA423 accelerometer.\n\nThis screen must initialize the accelerometer, retrieve the stored step count, and display it in a readable format. All accelerometer related functionality should be implemented using the Accel class within accel.h and accel.cpp. The screen logic should then be driven from main.cpp.\n\n**Implementation Guidance**\n- Initialize the BMA423 before attempting to read step data\n- Use the provided accelerometer abstraction rather than accessing registers directly\n- Ensure the displayed step count reflects the value stored in the sensor"},
    {"title": "Task 3: Design the Wi-Fi Status Screen", "content": "Create a screen that displays the current Wi-Fi connection status of the smartwatch.\n\nThe screen must support three states:\n- Wi-Fi Connected\n- Wi-Fi Connecting\n- Wi-Fi Not Connected\n\nWhen Wi-Fi is connected, the network SSID should be displayed. When Wi-Fi is not connected, the screen should clearly indicate that no connection is present. When a connection attempt is in progress, the screen should reflect the connecting state.\n\nYou must also implement a button that allows the user to manually attempt to reconnect to the Wi-Fi network.\n\nAll Wi-Fi related functionality should be implemented in mywifi.h and mywifi.cpp using the MyWiFi class, with high level control handled in main.cpp.\n\n**Implementation Guidance**\n- Track Wi-Fi state internally and update the screen accordingly\n- Use the provided drawWiFiSymbol and drawRefreshSymbol helper functions to display icons\n- Ensure screen updates are responsive but not excessively frequent", "videos": [{"url": "/api/videos/wifi-smartwatch.mp4", "title": "WiFi Smartwatch Demo", "type": "r2"}]},
    {"title": "Deliverables and File Structure", "content": "All code for this module must follow the structure below:\n\n- **touch.h** and **touch.c** handles FT6236U communication and coordinate extraction\n- **accel.h** and **accel.cpp** handles BMA423 initialization and step count retrieval\n- **mywifi.h** and **mywifi.cpp** handles Wi-Fi state management and reconnection logic\n- **display.h** and **display.cpp** handles rendering of all screens and symbols\n- **main.cpp** coordinates screen selection, input handling, and system behavior\n\nLow level drivers should not be implemented directly inside main.cpp. All functionality should be abstracted into appropriate modules."}
  ]
}'
WHERE id = 'lesson-project-mod3';
